import { Badge, BadgeTier } from "../types/game";

export const BADGE_TIER_COLORS: Record<BadgeTier, string> = {
  Bronze: "#CD7F32",
  Silver: "#C0C0C0",
  Gold: "#FFD700",
  Platinum: "#E5E4E2",
  Mythic: "#FF1493",
  Ascended: "#00FFFF",
  Eternal: "#9370DB",
  Transcendent: "#FFE4B5",
};

export const INITIAL_BADGES: Badge[] = [
  {
    id: "quotes_10",
    name: "Novice Reader",
    description: "Read 10 quotes",
    unlocked: false,
    xpReward: 50,
    category: "quotes",
    tier: "Bronze",
  },
  {
    id: "quotes_100",
    name: "Dedicated Reader",
    description: "Read 100 quotes",
    unlocked: false,
    xpReward: 200,
    category: "quotes",
    tier: "Silver",
  },
  {
    id: "quotes_1000",
    name: "Master of Wisdom",
    description: "Read 1,000 quotes",
    unlocked: false,
    xpReward: 1000,
    category: "quotes",
    tier: "Gold",
  },
  {
    id: "quotes_5000",
    name: "Unyielding Seeker",
    description: "Read 5,000 quotes",
    unlocked: false,
    xpReward: 3000,
    category: "quotes",
    tier: "Platinum",
  },
  {
    id: "quotes_10000",
    name: "Endless Library Walker",
    description: "Read 10,000 quotes",
    unlocked: false,
    xpReward: 8000,
    category: "quotes",
    tier: "Mythic",
  },
  {
    id: "quotes_25000",
    name: "Voice of a Thousand Dawns",
    description: "Read 25,000 quotes",
    unlocked: false,
    xpReward: 15000,
    category: "quotes",
    tier: "Ascended",
  },
  {
    id: "quotes_50000",
    name: "Keeper of Infinite Scrolls",
    description: "Read 50,000 quotes",
    unlocked: false,
    xpReward: 30000,
    category: "quotes",
    tier: "Ascended",
  },
  {
    id: "quotes_100000",
    name: "Walker Between Worlds",
    description: "Read 100,000 quotes",
    unlocked: false,
    xpReward: 60000,
    category: "quotes",
    tier: "Eternal",
  },
  {
    id: "quotes_250000",
    name: "Living Oracle of Ages",
    description: "Read 250,000 quotes",
    unlocked: false,
    xpReward: 120000,
    category: "quotes",
    tier: "Eternal",
  },
  {
    id: "quotes_500000",
    name: "Embodiment of Wisdom",
    description: "Read 500,000 quotes",
    unlocked: false,
    xpReward: 250000,
    category: "quotes",
    tier: "Transcendent",
  },
  {
    id: "quotes_1000000",
    name: "The Word Made Flesh",
    description: "Read 1,000,000 quotes",
    unlocked: false,
    xpReward: 500000,
    category: "quotes",
    tier: "Transcendent",
  },
  {
    id: "files_5",
    name: "Collector",
    description: "Upload 5 files",
    unlocked: false,
    xpReward: 100,
    category: "files",
    tier: "Bronze",
  },
  {
    id: "files_10",
    name: "Archivist",
    description: "Upload 10 files",
    unlocked: false,
    xpReward: 250,
    category: "files",
    tier: "Silver",
  },
  {
    id: "files_25",
    name: "Library Keeper",
    description: "Upload 25 files",
    unlocked: false,
    xpReward: 500,
    category: "files",
    tier: "Gold",
  },
  {
    id: "files_50",
    name: "Scriptorium Architect",
    description: "Upload 50 files",
    unlocked: false,
    xpReward: 1200,
    category: "files",
    tier: "Platinum",
  },
  {
    id: "files_100",
    name: "Custodian of Tomes",
    description: "Upload 100 files",
    unlocked: false,
    xpReward: 3000,
    category: "files",
    tier: "Mythic",
  },
  {
    id: "boons_10",
    name: "First Fortune",
    description: "Collect 10 boons",
    unlocked: false,
    xpReward: 100,
    category: "boons",
    tier: "Bronze",
  },
  {
    id: "boons_50",
    name: "Rising Treasury",
    description: "Collect 50 boons",
    unlocked: false,
    xpReward: 300,
    category: "boons",
    tier: "Silver",
  },
  {
    id: "boons_100",
    name: "Vault of Echoes",
    description: "Collect 100 boons",
    unlocked: false,
    xpReward: 800,
    category: "boons",
    tier: "Gold",
  },
  {
    id: "boons_250",
    name: "Radiant Reliquary",
    description: "Collect 250 boons",
    unlocked: false,
    xpReward: 2000,
    category: "boons",
    tier: "Platinum",
  },
  {
    id: "boons_500",
    name: "Living Hoard",
    description: "Collect 500 boons",
    unlocked: false,
    xpReward: 5000,
    category: "boons",
    tier: "Mythic",
  },
  {
    id: "boons_1000",
    name: "Archive of Wonders",
    description: "Collect 1,000 boons",
    unlocked: false,
    xpReward: 10000,
    category: "boons",
    tier: "Ascended",
  },
  {
    id: "boons_2500",
    name: "Treasury of Ages",
    description: "Collect 2,500 boons",
    unlocked: false,
    xpReward: 25000,
    category: "boons",
    tier: "Ascended",
  },
  {
    id: "boons_5000",
    name: "Vault of Eternity",
    description: "Collect 5,000 boons",
    unlocked: false,
    xpReward: 50000,
    category: "boons",
    tier: "Eternal",
  },
  {
    id: "boons_10000",
    name: "Museum of Infinite Relics",
    description: "Collect 10,000 boons",
    unlocked: false,
    xpReward: 100000,
    category: "boons",
    tier: "Eternal",
  },
  {
    id: "boons_25000",
    name: "Sanctum of All Treasures",
    description: "Collect 25,000 boons",
    unlocked: false,
    xpReward: 250000,
    category: "boons",
    tier: "Transcendent",
  },
  {
    id: "boons_50000",
    name: "Keeper of Every Wonder",
    description: "Collect 50,000 boons",
    unlocked: false,
    xpReward: 500000,
    category: "boons",
    tier: "Transcendent",
  },
  {
    id: "rare_1",
    name: "Glimpse of Rarity",
    description: "Obtain 1 Rare+ boon",
    unlocked: false,
    xpReward: 100,
    category: "boons",
    tier: "Bronze",
  },
  {
    id: "rare_10",
    name: "Seeker of the Uncommon",
    description: "Obtain 10 Rare+ boons",
    unlocked: false,
    xpReward: 400,
    category: "boons",
    tier: "Silver",
  },
  {
    id: "rare_25",
    name: "Collector of Wonders",
    description: "Obtain 25 Rare+ boons",
    unlocked: false,
    xpReward: 1000,
    category: "boons",
    tier: "Gold",
  },
  {
    id: "rare_50",
    name: "Master of Rarities",
    description: "Obtain 50 Rare+ boons",
    unlocked: false,
    xpReward: 2500,
    category: "boons",
    tier: "Platinum",
  },
  {
    id: "rare_100",
    name: "Keeper of the Impossible",
    description: "Obtain 100 Rare+ boons",
    unlocked: false,
    xpReward: 6000,
    category: "boons",
    tier: "Mythic",
  },
  {
    id: "rare_250",
    name: "Curator of Legends",
    description: "Obtain 250 Rare+ boons",
    unlocked: false,
    xpReward: 15000,
    category: "boons",
    tier: "Ascended",
  },
  {
    id: "rare_500",
    name: "Master of Mythic Treasures",
    description: "Obtain 500 Rare+ boons",
    unlocked: false,
    xpReward: 30000,
    category: "boons",
    tier: "Ascended",
  },
  {
    id: "rare_1000",
    name: "Eternal Collector of Rarities",
    description: "Obtain 1,000 Rare+ boons",
    unlocked: false,
    xpReward: 60000,
    category: "boons",
    tier: "Eternal",
  },
  {
    id: "rare_2500",
    name: "Transcendent Vault Keeper",
    description: "Obtain 2,500 Rare+ boons",
    unlocked: false,
    xpReward: 150000,
    category: "boons",
    tier: "Transcendent",
  },
  {
    id: "legendary_1",
    name: "First Legend",
    description: "Obtain your first Legendary boon",
    unlocked: false,
    xpReward: 500,
    category: "boons",
    tier: "Bronze",
  },
  {
    id: "legendary_3",
    name: "Touched by Destiny",
    description: "Obtain 3 Legendary boons",
    unlocked: false,
    xpReward: 1500,
    category: "boons",
    tier: "Silver",
  },
  {
    id: "legendary_5",
    name: "Bearer of Myths",
    description: "Obtain 5 Legendary boons",
    unlocked: false,
    xpReward: 3000,
    category: "boons",
    tier: "Gold",
  },
  {
    id: "legendary_10",
    name: "Living Legend",
    description: "Obtain 10 Legendary boons",
    unlocked: false,
    xpReward: 6000,
    category: "boons",
    tier: "Platinum",
  },
  {
    id: "legendary_20",
    name: "Herald of the Eternal",
    description: "Obtain 20 Legendary boons",
    unlocked: false,
    xpReward: 12000,
    category: "boons",
    tier: "Mythic",
  },
  {
    id: "legendary_50",
    name: "Master of Legendary Artifacts",
    description: "Obtain 50 Legendary boons",
    unlocked: false,
    xpReward: 30000,
    category: "boons",
    tier: "Ascended",
  },
  {
    id: "legendary_100",
    name: "Collector of Impossibilities",
    description: "Obtain 100 Legendary boons",
    unlocked: false,
    xpReward: 60000,
    category: "boons",
    tier: "Ascended",
  },
  {
    id: "legendary_250",
    name: "Eternal Legend Bearer",
    description: "Obtain 250 Legendary boons",
    unlocked: false,
    xpReward: 150000,
    category: "boons",
    tier: "Eternal",
  },
  {
    id: "legendary_500",
    name: "Transcendent Mythkeeper",
    description: "Obtain 500 Legendary boons",
    unlocked: false,
    xpReward: 300000,
    category: "boons",
    tier: "Eternal",
  },
  {
    id: "legendary_1000",
    name: "Living Repository of Legends",
    description: "Obtain 1,000 Legendary boons",
    unlocked: false,
    xpReward: 600000,
    category: "boons",
    tier: "Transcendent",
  },
  {
    id: "streak_7",
    name: "Weekly Devotion",
    description: "Maintain a 7-day streak",
    unlocked: false,
    xpReward: 300,
    category: "streaks",
    tier: "Bronze",
  },
  {
    id: "streak_30",
    name: "Monthly Dedication",
    description: "Maintain a 30-day streak",
    unlocked: false,
    xpReward: 1500,
    category: "streaks",
    tier: "Silver",
  },
  {
    id: "streak_100",
    name: "Keeper of the Flame",
    description: "Maintain a 100-day streak",
    unlocked: false,
    xpReward: 5000,
    category: "streaks",
    tier: "Gold",
  },
  {
    id: "streak_365",
    name: "Year of the Living Word",
    description: "Maintain a 365-day streak",
    unlocked: false,
    xpReward: 20000,
    category: "streaks",
    tier: "Mythic",
  },
  {
    id: "level_25",
    name: "Awakened Initiate",
    description: "Reach level 25",
    unlocked: false,
    xpReward: 500,
    category: "level",
    tier: "Bronze",
  },
  {
    id: "level_50",
    name: "Rising Adept",
    description: "Reach level 50",
    unlocked: false,
    xpReward: 1500,
    category: "level",
    tier: "Silver",
  },
  {
    id: "level_100",
    name: "Luminary of the Forge",
    description: "Reach level 100",
    unlocked: false,
    xpReward: 5000,
    category: "level",
    tier: "Gold",
  },
  {
    id: "level_150",
    name: "Keeper of the Constellations",
    description: "Reach level 150",
    unlocked: false,
    xpReward: 10000,
    category: "level",
    tier: "Platinum",
  },
  {
    id: "level_200",
    name: "Mythic Wayfarer",
    description: "Reach level 200",
    unlocked: false,
    xpReward: 20000,
    category: "level",
    tier: "Mythic",
  },
  {
    id: "level_300",
    name: "Ascended Soul",
    description: "Reach level 300",
    unlocked: false,
    xpReward: 40000,
    category: "level",
    tier: "Ascended",
  },
  {
    id: "level_500",
    name: "Eternal Luminary",
    description: "Reach level 500",
    unlocked: false,
    xpReward: 80000,
    category: "level",
    tier: "Eternal",
  },
  {
    id: "level_750",
    name: "Transcendent Being",
    description: "Reach level 750",
    unlocked: false,
    xpReward: 150000,
    category: "level",
    tier: "Transcendent",
  },
  {
    id: "level_1000",
    name: "Beyond Mortal Reckoning",
    description: "Reach level 1000",
    unlocked: false,
    xpReward: 300000,
    category: "level",
    tier: "Transcendent",
  },
  {
    id: "destiny_disciple",
    name: "Path of the Disciple",
    description: "Reach Disciple tier",
    unlocked: false,
    xpReward: 500,
    category: "destiny",
    tier: "Bronze",
  },
  {
    id: "destiny_adept",
    name: "Ascended Adept",
    description: "Reach Adept tier",
    unlocked: false,
    xpReward: 2000,
    category: "destiny",
    tier: "Silver",
  },
  {
    id: "destiny_master",
    name: "Crowned Master",
    description: "Reach Master tier",
    unlocked: false,
    xpReward: 8000,
    category: "destiny",
    tier: "Gold",
  },
  {
    id: "destiny_mythic",
    name: "Eternal Mythic",
    description: "Reach Mythic tier",
    unlocked: false,
    xpReward: 20000,
    category: "destiny",
    tier: "Mythic",
  },
  {
    id: "destiny_ascended",
    name: "Soul Ascended",
    description: "Reach Ascended tier",
    unlocked: false,
    xpReward: 50000,
    category: "destiny",
    tier: "Ascended",
  },
  {
    id: "destiny_eternal",
    name: "Eternally Bound",
    description: "Reach Eternal tier",
    unlocked: false,
    xpReward: 100000,
    category: "destiny",
    tier: "Eternal",
  },
  {
    id: "destiny_transcendent",
    name: "Transcended Form",
    description: "Reach Transcendent tier",
    unlocked: false,
    xpReward: 200000,
    category: "destiny",
    tier: "Transcendent",
  },
  {
    id: "destiny_omniscient",
    name: "Omniscient Vessel",
    description: "Reach Omniscient tier",
    unlocked: false,
    xpReward: 500000,
    category: "destiny",
    tier: "Transcendent",
  },
  {
    id: "time_30",
    name: "First Watch",
    description: "Quest for 30 minutes",
    unlocked: false,
    xpReward: 100,
    category: "time",
    tier: "Bronze",
  },
  {
    id: "time_120",
    name: "Steadfast Seeker",
    description: "Quest for 2 hours",
    unlocked: false,
    xpReward: 300,
    category: "time",
    tier: "Silver",
  },
  {
    id: "time_360",
    name: "Devoted Wanderer",
    description: "Quest for 6 hours",
    unlocked: false,
    xpReward: 800,
    category: "time",
    tier: "Gold",
  },
  {
    id: "time_1200",
    name: "Keeper of Hours",
    description: "Quest for 20 hours",
    unlocked: false,
    xpReward: 2000,
    category: "time",
    tier: "Platinum",
  },
  {
    id: "time_3000",
    name: "Eternal Pilgrim",
    description: "Quest for 50 hours",
    unlocked: false,
    xpReward: 5000,
    category: "time",
    tier: "Mythic",
  },
  {
    id: "time_6000",
    name: "Timeless Wanderer",
    description: "Quest for 100 hours",
    unlocked: false,
    xpReward: 10000,
    category: "time",
    tier: "Ascended",
  },
  {
    id: "time_18000",
    name: "Devoted Lifetime",
    description: "Quest for 300 hours",
    unlocked: false,
    xpReward: 30000,
    category: "time",
    tier: "Ascended",
  },
  {
    id: "time_36000",
    name: "Years in Service",
    description: "Quest for 600 hours",
    unlocked: false,
    xpReward: 60000,
    category: "time",
    tier: "Eternal",
  },
  {
    id: "time_60000",
    name: "Eternal Meditation",
    description: "Quest for 1000 hours",
    unlocked: false,
    xpReward: 100000,
    category: "time",
    tier: "Eternal",
  },
  {
    id: "time_120000",
    name: "Beyond Time Itself",
    description: "Quest for 2000 hours",
    unlocked: false,
    xpReward: 250000,
    category: "time",
    tier: "Transcendent",
  },
  {
    id: "streak_500",
    name: "Unbroken Devotion",
    description: "Maintain a 500-day streak",
    unlocked: false,
    xpReward: 50000,
    category: "streaks",
    tier: "Ascended",
  },
  {
    id: "streak_1000",
    name: "Millennium Walker",
    description: "Maintain a 1000-day streak",
    unlocked: false,
    xpReward: 100000,
    category: "streaks",
    tier: "Eternal",
  },
  {
    id: "streak_1825",
    name: "Five Years of Light",
    description: "Maintain a 1825-day streak (5 years)",
    unlocked: false,
    xpReward: 250000,
    category: "streaks",
    tier: "Transcendent",
  },
  {
    id: "streak_3650",
    name: "Decade of Unwavering Faith",
    description: "Maintain a 3650-day streak (10 years)",
    unlocked: false,
    xpReward: 1000000,
    category: "streaks",
    tier: "Transcendent",
  },
];
