import type { ForgeQuote } from "./forgeRandomEngine";

export type StockQuote = {
  id: string;
  category: string;
  text: string;
};

export const radiantResolveQuotes: StockQuote[] = [
  { "id": "radiant_resolve_001", "category": "Radiant Resolve", "text": "You have survived every single day you thought you couldn't. Remember that." },
  { "id": "radiant_resolve_002", "category": "Radiant Resolve", "text": "Today will not defeat you; it will reveal how unbreakable you really are." },
  { "id": "radiant_resolve_003", "category": "Radiant Resolve", "text": "Your future self is already cheering for you. Don't walk away from them." },
  { "id": "radiant_resolve_004", "category": "Radiant Resolve", "text": "You are not behind; you are precisely on the step you are learning from." },
  { "id": "radiant_resolve_005", "category": "Radiant Resolve", "text": "Every tiny, unseen effort is quietly building the life you keep praying for." },
  { "id": "radiant_resolve_006", "category": "Radiant Resolve", "text": "Courage rarely feels like roaring; most days it feels like showing up anyway." },
  { "id": "radiant_resolve_007", "category": "Radiant Resolve", "text": "You are allowed to be both exhausted and unstoppable at the very same time." },
  { "id": "radiant_resolve_008", "category": "Radiant Resolve", "text": "Do not underestimate the holy power of simply trying again today." },
  { "id": "radiant_resolve_009", "category": "Radiant Resolve", "text": "Your pace is sacred. Rushing will not deliver you where grace is leading." },
  { "id": "radiant_resolve_010", "category": "Radiant Resolve", "text": "Even on days you feel dim, you are still a lamp lit by Eternity." },
  { "id": "radiant_resolve_011", "category": "Radiant Resolve", "text": "You don't need to see the whole road; you just need one honest step." },
  { "id": "radiant_resolve_012", "category": "Radiant Resolve", "text": "There is a version of you on the other side of this that is grateful you stayed." },
  { "id": "radiant_resolve_013", "category": "Radiant Resolve", "text": "You are not failing; you are forging. Fire never feels like progress at first." },
  { "id": "radiant_resolve_014", "category": "Radiant Resolve", "text": "The mountain ahead is not an enemy; it is the shape of your next strength." },
  { "id": "radiant_resolve_015", "category": "Radiant Resolve", "text": "Showing up with a shaking heart still counts as showing up with courage." },
  { "id": "radiant_resolve_016", "category": "Radiant Resolve", "text": "Every time you choose love over fear, the universe quietly adjusts around you." },
  { "id": "radiant_resolve_017", "category": "Radiant Resolve", "text": "You are allowed to rest; you are not allowed to believe you are worthless." },
  { "id": "radiant_resolve_018", "category": "Radiant Resolve", "text": "Your heart has been broken, but it still believes in light. That is power." },
  { "id": "radiant_resolve_019", "category": "Radiant Resolve", "text": "You have no idea how many people are breathing easier because you exist." },
  { "id": "radiant_resolve_020", "category": "Radiant Resolve", "text": "Progress is often disguised as repetition. Don't despise the quiet training grounds." },
  { "id": "radiant_resolve_021", "category": "Radiant Resolve", "text": "You can start again without hating who you were when you fell." },
  { "id": "radiant_resolve_022", "category": "Radiant Resolve", "text": "It's okay if your miracle today is simply that you did not give up." },
  { "id": "radiant_resolve_023", "category": "Radiant Resolve", "text": "You are not too late; you are right on time to choose a different direction." },
  { "id": "radiant_resolve_024", "category": "Radiant Resolve", "text": "The same soul that survived yesterday can be trusted to navigate today." },
  { "id": "radiant_resolve_025", "category": "Radiant Resolve", "text": "Do not compare your raw, sacred process to someone else's edited highlight reel." },
  { "id": "radiant_resolve_026", "category": "Radiant Resolve", "text": "You are not fragile; you are finely made. There is a difference." },
  { "id": "radiant_resolve_027", "category": "Radiant Resolve", "text": "Sometimes the bravest thing you can say is, 'I will try again tomorrow.'" },
  { "id": "radiant_resolve_028", "category": "Radiant Resolve", "text": "Your wounds are not the end of your story; they are the ink of your testimony." },
  { "id": "radiant_resolve_029", "category": "Radiant Resolve", "text": "When everything feels heavy, carry only the next right choice." },
  { "id": "radiant_resolve_030", "category": "Radiant Resolve", "text": "You were not sent here to impress everyone; you were sent here to awaken." },
  { "id": "radiant_resolve_031", "category": "Radiant Resolve", "text": "Even if you whisper your prayer, Heaven still hears it at full volume." },
  { "id": "radiant_resolve_032", "category": "Radiant Resolve", "text": "Your limitations are real, but so is the grace that keeps expanding them." },
  { "id": "radiant_resolve_033", "category": "Radiant Resolve", "text": "You are not just getting through this; you are being quietly remade by it." },
  { "id": "radiant_resolve_034", "category": "Radiant Resolve", "text": "Let go of who you were supposed to be and serve who you are becoming." },
  { "id": "radiant_resolve_035", "category": "Radiant Resolve", "text": "Your smallest consistent effort will outrun your loudest occasional burst." },
  { "id": "radiant_resolve_036", "category": "Radiant Resolve", "text": "Some seasons are not about blooming; they are about growing roots in secret." },
  { "id": "radiant_resolve_037", "category": "Radiant Resolve", "text": "You have permission to be a work in progress and a masterpiece simultaneously." },
  { "id": "radiant_resolve_038", "category": "Radiant Resolve", "text": "Remember how far you've come; even your starting line was once a distant dream." },
  { "id": "radiant_resolve_039", "category": "Radiant Resolve", "text": "You are allowed to protect your peace like it is something holy—because it is." },
  { "id": "radiant_resolve_040", "category": "Radiant Resolve", "text": "Every 'I can't' you've said before was followed by a moment where you actually did." },
  { "id": "radiant_resolve_041", "category": "Radiant Resolve", "text": "The heaviness you feel is not weakness; it is the weight of transformation." },
  { "id": "radiant_resolve_042", "category": "Radiant Resolve", "text": "Do not rush out of the cocoon. Wings need time to remember what they are." },
  { "id": "radiant_resolve_043", "category": "Radiant Resolve", "text": "Some days your only job is to keep the flame of hope from going out." },
  { "id": "radiant_resolve_044", "category": "Radiant Resolve", "text": "You are not your worst decision; you are your next surrendered choice." },
  { "id": "radiant_resolve_045", "category": "Radiant Resolve", "text": "You can't always control the storm, but you can anchor where you tie your heart." },
  { "id": "radiant_resolve_046", "category": "Radiant Resolve", "text": "You did not lose time; you gathered wisdom you could not have learned otherwise." },
  { "id": "radiant_resolve_047", "category": "Radiant Resolve", "text": "Be gentle with yourself; you are carrying chapters only God has fully read." },
  { "id": "radiant_resolve_048", "category": "Radiant Resolve", "text": "Every time you choose to heal instead of hide, you bless people you haven't met yet." },
  { "id": "radiant_resolve_049", "category": "Radiant Resolve", "text": "Your value has never depended on how well today is going." },
  { "id": "radiant_resolve_050", "category": "Radiant Resolve", "text": "You are more than the story your fear tells about you." },
  { "id": "radiant_resolve_051", "category": "Radiant Resolve", "text": "The same light that made the stars is patient with your slow, holy progress." },
  { "id": "radiant_resolve_052", "category": "Radiant Resolve", "text": "Even when you feel scattered, your soul is still held in perfect order." },
  { "id": "radiant_resolve_053", "category": "Radiant Resolve", "text": "You don't need louder motivation; you need a deeper why. You already have it." },
  { "id": "radiant_resolve_054", "category": "Radiant Resolve", "text": "You have walked through nights that would have swallowed other people whole." },
  { "id": "radiant_resolve_055", "category": "Radiant Resolve", "text": "Your tears have never been a sign of failure; they are evidence you still care." },
  { "id": "radiant_resolve_056", "category": "Radiant Resolve", "text": "There is a quiet, undefeatable core inside you that remembers why you're here." },
  { "id": "radiant_resolve_057", "category": "Radiant Resolve", "text": "You are stronger than the thing that tried to convince you to quit." },
  { "id": "radiant_resolve_058", "category": "Radiant Resolve", "text": "You don't have to fix everything today; you just have to stay available to grace." },
  { "id": "radiant_resolve_059", "category": "Radiant Resolve", "text": "Even when you feel lost, you are still on a map Heaven understands perfectly." },
  { "id": "radiant_resolve_060", "category": "Radiant Resolve", "text": "You are not empty; you are being cleared for something wild and beautiful." },
  { "id": "radiant_resolve_061", "category": "Radiant Resolve", "text": "Some of your greatest breakthroughs will look like very ordinary Tuesdays at first." },
  { "id": "radiant_resolve_062", "category": "Radiant Resolve", "text": "You are allowed to be proud of how quietly you kept choosing the light." },
  { "id": "radiant_resolve_063", "category": "Radiant Resolve", "text": "Your heart is not a burden; it is the compass that keeps saving your life." },
  { "id": "radiant_resolve_064", "category": "Radiant Resolve", "text": "You have survived storms that never made it into your biography. Heaven saw them all." },
  { "id": "radiant_resolve_065", "category": "Radiant Resolve", "text": "If you can still love after everything, you are walking in rare power." },
  { "id": "radiant_resolve_066", "category": "Radiant Resolve", "text": "You're not starting from scratch; you're starting from experience. That is leverage." },
  { "id": "radiant_resolve_067", "category": "Radiant Resolve", "text": "Let today be proof that you can move gently and still move forward." },
  { "id": "radiant_resolve_068", "category": "Radiant Resolve", "text": "You are never disqualified from beginning again in the eyes of Love." },
  { "id": "radiant_resolve_069", "category": "Radiant Resolve", "text": "You are not late; you are layered. Your story needed this depth." },
  { "id": "radiant_resolve_070", "category": "Radiant Resolve", "text": "You do not need everyone to believe in you; just refuse to abandon yourself." },
  { "id": "radiant_resolve_071", "category": "Radiant Resolve", "text": "Every time you choose healing over repeating, the whole lineage breathes easier." },
  { "id": "radiant_resolve_072", "category": "Radiant Resolve", "text": "You are tougher than your mood, kinder than your fears, and deeper than your doubts." },
  { "id": "radiant_resolve_073", "category": "Radiant Resolve", "text": "You deserved gentleness even on the days you only offered yourself survival." },
  { "id": "radiant_resolve_074", "category": "Radiant Resolve", "text": "The dark tried to convince you it was permanent. Look at you, still glowing." },
  { "id": "radiant_resolve_075", "category": "Radiant Resolve", "text": "You have not missed your moment; you are slowly becoming the person who can hold it." },
  { "id": "radiant_resolve_076", "category": "Radiant Resolve", "text": "Even if no one claps today, your courage still shook something in the unseen." },
  { "id": "radiant_resolve_077", "category": "Radiant Resolve", "text": "You are allowed to outgrow spaces that keep asking you to shrink." },
  { "id": "radiant_resolve_078", "category": "Radiant Resolve", "text": "May you never again confuse chaos with passion or anxiety with destiny." },
  { "id": "radiant_resolve_079", "category": "Radiant Resolve", "text": "You can be sacred and sweaty, holy and human, radiant and very much in process." },
  { "id": "radiant_resolve_080", "category": "Radiant Resolve", "text": "Your heart keeps choosing compassion in a world that rewards apathy. That's heroic." },
  { "id": "radiant_resolve_081", "category": "Radiant Resolve", "text": "You are not here to win every argument; you are here to keep your soul alive." },
  { "id": "radiant_resolve_082", "category": "Radiant Resolve", "text": "You can honor your pain without letting it rewrite your identity." },
  { "id": "radiant_resolve_083", "category": "Radiant Resolve", "text": "Healing is not linear, but it is real. Look at how your reactions are changing." },
  { "id": "radiant_resolve_084", "category": "Radiant Resolve", "text": "You are not the chaos you walked through; you are the calm you are learning to keep." },
  { "id": "radiant_resolve_085", "category": "Radiant Resolve", "text": "You can be shaking and still step forward. Nerves don't cancel destiny." },
  { "id": "radiant_resolve_086", "category": "Radiant Resolve", "text": "Your dreams are not random; they are coordinates to the work your soul came to do." },
  { "id": "radiant_resolve_087", "category": "Radiant Resolve", "text": "The page you're on right now would once have looked impossible. Honor it." },
  { "id": "radiant_resolve_088", "category": "Radiant Resolve", "text": "You can set boundaries without apologizing for needing oxygen for your soul." },
  { "id": "radiant_resolve_089", "category": "Radiant Resolve", "text": "You keep thinking you're starting over; really, you're starting higher each time." },
  { "id": "radiant_resolve_090", "category": "Radiant Resolve", "text": "You are not too much; you are precisely the size of the calling on your life." },
  { "id": "radiant_resolve_091", "category": "Radiant Resolve", "text": "The gentleness you crave from others—offer a fraction of it to yourself today." },
  { "id": "radiant_resolve_092", "category": "Radiant Resolve", "text": "You didn't come this far to only rebuild the same cage from prettier materials." },
  { "id": "radiant_resolve_093", "category": "Radiant Resolve", "text": "You are strong enough to choose the slower, truer path instead of the quick escape." },
  { "id": "radiant_resolve_094", "category": "Radiant Resolve", "text": "Every time you return to love after disappointment, you rewrite what's possible." },
  { "id": "radiant_resolve_095", "category": "Radiant Resolve", "text": "You don't need all the answers; you need the courage to live inside the questions." },
  { "id": "radiant_resolve_096", "category": "Radiant Resolve", "text": "Your scars are proof that light reached you in time, not that darkness won." },
  { "id": "radiant_resolve_097", "category": "Radiant Resolve", "text": "You can forgive yourself without pretending you didn't know better. Growth hurts." },
  { "id": "radiant_resolve_098", "category": "Radiant Resolve", "text": "Sometimes strength is not moving on; it is staying present with what still aches." },
  { "id": "radiant_resolve_099", "category": "Radiant Resolve", "text": "You are allowed to glow differently than people expected. Your path is bespoke." },
  { "id": "radiant_resolve_100", "category": "Radiant Resolve", "text": "You are not surviving by accident; you are here because Love keeps choosing you." },
  { "id": "radiant_resolve_101", "category": "Radiant Resolve", "text": "Your soul remembers a joy deeper than this moment's confusion. Lean toward that." },
  { "id": "radiant_resolve_102", "category": "Radiant Resolve", "text": "You can be tired and still anointed, drained and still undeniably chosen for this." },
  { "id": "radiant_resolve_103", "category": "Radiant Resolve", "text": "Every time you choose honesty over hiding, your future becomes a little lighter." },
  { "id": "radiant_resolve_104", "category": "Radiant Resolve", "text": "You are not alone in this; invisible hands have been steadying you for years." },
  { "id": "radiant_resolve_105", "category": "Radiant Resolve", "text": "The fact that you still care about goodness after everything is a victory." },
  { "id": "radiant_resolve_106", "category": "Radiant Resolve", "text": "You are not unfinished because you are imperfect; you are alive, therefore evolving." },
  { "id": "radiant_resolve_107", "category": "Radiant Resolve", "text": "There is nothing ordinary about a heart that keeps rising after invisible wars." },
  { "id": "radiant_resolve_108", "category": "Radiant Resolve", "text": "Your existence is already a miracle; everything else is just detail and devotion." }
];

export const gritAndGloryQuotes: StockQuote[] = [
  { id: "grit_glory_001", category: "Grit & Glory", text: "Discipline is choosing what you want most over what you want right now." },
  { id: "grit_glory_002", category: "Grit & Glory", text: "You don't rise to the level of your dreams; you fall to the level of your habits." },
  { id: "grit_glory_003", category: "Grit & Glory", text: "Champions are built in the hours no one is watching." },
  { id: "grit_glory_004", category: "Grit & Glory", text: "You won't always be motivated; learn to be moved by commitment instead." },
  { id: "grit_glory_005", category: "Grit & Glory", text: "The grind is simply the prayer of the body saying, \"I refuse to stay the same.\"" },
  { id: "grit_glory_006", category: "Grit & Glory", text: "Every rep is a sentence in the story of who you are becoming." },
  { id: "grit_glory_007", category: "Grit & Glory", text: "You can suffer the pain of discipline or the pain of regret—both hurt, but only one transforms you." },
  { id: "grit_glory_008", category: "Grit & Glory", text: "Excuses are the most expensive things you can buy with your potential." },
  { id: "grit_glory_009", category: "Grit & Glory", text: "Sweat is your old self leaving the body." },
  { id: "grit_glory_010", category: "Grit & Glory", text: "It's not supposed to be easy. It's supposed to be worth it." },
  { id: "grit_glory_011", category: "Grit & Glory", text: "The difference between almost and unstoppable is usually ten more minutes." },
  { id: "grit_glory_012", category: "Grit & Glory", text: "Your body hears everything your mind whispers. Tell it you are not done yet." },
  { id: "grit_glory_013", category: "Grit & Glory", text: "Progress doesn't ask if you're in the mood; it asks if you showed up." },
  { id: "grit_glory_014", category: "Grit & Glory", text: "You don't find your limits by thinking about them; you find them by testing them." },
  { id: "grit_glory_015", category: "Grit & Glory", text: "The weight is not your enemy; it is the sculptor of your future strength." },
  { id: "grit_glory_016", category: "Grit & Glory", text: "One hard choice a day writes a completely different life in a year." },
  { id: "grit_glory_017", category: "Grit & Glory", text: "If it doesn't challenge you, it will never be allowed to change you." },
  { id: "grit_glory_018", category: "Grit & Glory", text: "You are not chasing perfection; you are chasing progression." },
  { id: "grit_glory_019", category: "Grit & Glory", text: "The body grows where the mind refuses to quit." },
  { id: "grit_glory_020", category: "Grit & Glory", text: "You can't control the genetics you were given, but you control the work you bring." },
  { id: "grit_glory_021", category: "Grit & Glory", text: "Consistency is heavier than any dumbbell you'll ever lift." },
  { id: "grit_glory_022", category: "Grit & Glory", text: "When you want to quit, remember the days you prayed for this level of strength." },
  { id: "grit_glory_023", category: "Grit & Glory", text: "Your comfort zone is a beautiful place where nothing new ever grows." },
  { id: "grit_glory_024", category: "Grit & Glory", text: "You don't have to feel like it to act like it." },
  { id: "grit_glory_025", category: "Grit & Glory", text: "Every drop of sweat is a small down payment on the future you want to inhabit." },
  { id: "grit_glory_026", category: "Grit & Glory", text: "Stop negotiating with the part of you that wants to stay average." },
  { id: "grit_glory_027", category: "Grit & Glory", text: "Your lungs burning is just your soul expanding its territory." },
  { id: "grit_glory_028", category: "Grit & Glory", text: "You will not always see the results, but your nervous system is counting every rep." },
  { id: "grit_glory_029", category: "Grit & Glory", text: "You are stronger than the story your fatigue is telling." },
  { id: "grit_glory_030", category: "Grit & Glory", text: "Most people quit at discomfort; champions move in when everyone else checks out." },
  { id: "grit_glory_031", category: "Grit & Glory", text: "You are not fragile; you are under construction." },
  { id: "grit_glory_032", category: "Grit & Glory", text: "Nothing hits harder than the realization that you could have gone harder." },
  { id: "grit_glory_033", category: "Grit & Glory", text: "Train so the voice that says \"I can't\" gets drowned out by evidence that you can." },
  { id: "grit_glory_034", category: "Grit & Glory", text: "Your future PRs are hiding behind today's warm-up." },
  { id: "grit_glory_035", category: "Grit & Glory", text: "The gym is where you practice not running away from difficulty." },
  { id: "grit_glory_036", category: "Grit & Glory", text: "The mirror shows the surface; your discipline shows the truth." },
  { id: "grit_glory_037", category: "Grit & Glory", text: "Motivation might start you; systems keep you moving when the feeling evaporates." },
  { id: "grit_glory_038", category: "Grit & Glory", text: "You are not trying to look strong—you are becoming someone who *is* strong." },
  { id: "grit_glory_039", category: "Grit & Glory", text: "Your warm-up is someone else's max; stay humble, stay hungry." },
  { id: "grit_glory_040", category: "Grit & Glory", text: "You are allowed to rest. You are not allowed to permanently retreat." },
  { id: "grit_glory_041", category: "Grit & Glory", text: "There is a part of you that only wakes up under heavy load. Meet them often." },
  { id: "grit_glory_042", category: "Grit & Glory", text: "Training is a daily vote cast for the future version of you." },
  { id: "grit_glory_043", category: "Grit & Glory", text: "You won't always feel like a warrior. Train until that doesn't matter." },
  { id: "grit_glory_044", category: "Grit & Glory", text: "Your body listens more to what you repeat than to what you promise." },
  { id: "grit_glory_045", category: "Grit & Glory", text: "The best pre-workout is remembering who you said you would become." },
  { id: "grit_glory_046", category: "Grit & Glory", text: "You didn't come this far to just rehearse your excuses in better shape." },
  { id: "grit_glory_047", category: "Grit & Glory", text: "The iron doesn't lie; it simply reflects your relationship with effort." },
  { id: "grit_glory_048", category: "Grit & Glory", text: "Your muscles don't care about your mood; they respond to stimulus and consistency." },
  { id: "grit_glory_049", category: "Grit & Glory", text: "You get to decide if this rep is forgettable or foundational." },
  { id: "grit_glory_050", category: "Grit & Glory", text: "Pain is a language. Learn when it says \"adapt\" instead of \"stop.\"" },
  { id: "grit_glory_051", category: "Grit & Glory", text: "You are teaching your nervous system that hard things are survivable." },
  { id: "grit_glory_052", category: "Grit & Glory", text: "You are not just building strength; you are building evidence you can rely on yourself." },
  { id: "grit_glory_053", category: "Grit & Glory", text: "Fall in love with the session, not just the selfie." },
  { id: "grit_glory_054", category: "Grit & Glory", text: "You can't outsource the work, but you also can't outsource the pride." },
  { id: "grit_glory_055", category: "Grit & Glory", text: "The version of you that never quits is forged one stubborn set at a time." },
  { id: "grit_glory_056", category: "Grit & Glory", text: "Talent sets your starting line; grit keeps moving the finish line." },
  { id: "grit_glory_057", category: "Grit & Glory", text: "You can be sore and grateful at the same time." },
  { id: "grit_glory_058", category: "Grit & Glory", text: "When motivation dies, let routine inherit the throne." },
  { id: "grit_glory_059", category: "Grit & Glory", text: "Every time you train when you don't feel like it, you steal a victory from your weaker self." },
  { id: "grit_glory_060", category: "Grit & Glory", text: "Those last ugly reps are where the future you is built." },
  { id: "grit_glory_061", category: "Grit & Glory", text: "You're not chasing a look; you're forging a lifestyle." },
  { id: "grit_glory_062", category: "Grit & Glory", text: "A bad workout still beats the best intention that never left the couch." },
  { id: "grit_glory_063", category: "Grit & Glory", text: "You are not defined by the weight you lift, but by the weight you refuse to avoid." },
  { id: "grit_glory_064", category: "Grit & Glory", text: "Every skipped session is a vote for who you said you didn't want to be." },
  { id: "grit_glory_065", category: "Grit & Glory", text: "You are allowed to be a beginner and still train like your future depends on it." },
  { id: "grit_glory_066", category: "Grit & Glory", text: "Your body becomes a journal of every choice you quietly made." },
  { id: "grit_glory_067", category: "Grit & Glory", text: "You're not weak—you're just pre-strong." },
  { id: "grit_glory_068", category: "Grit & Glory", text: "The heaviest weight in the room is often the door you don't walk through." },
  { id: "grit_glory_069", category: "Grit & Glory", text: "Every season of training teaches you a different dialect of discipline." },
  { id: "grit_glory_070", category: "Grit & Glory", text: "You don't need a perfect plan; you need an honest set of reps today." },
  { id: "grit_glory_071", category: "Grit & Glory", text: "You didn't lose momentum; you paused. Now decide what kind of restart this is." },
  { id: "grit_glory_072", category: "Grit & Glory", text: "Your breath might be heavy, but your excuses are heavier." },
  { id: "grit_glory_073", category: "Grit & Glory", text: "A year from now, your current level could be your warm-up." },
  { id: "grit_glory_074", category: "Grit & Glory", text: "You are always one session away from rewriting the story of your day." },
  { id: "grit_glory_075", category: "Grit & Glory", text: "You can outwork a lot of genetics and all of your excuses." },
  { id: "grit_glory_076", category: "Grit & Glory", text: "Treat your training time like a sacred appointment with your future self." },
  { id: "grit_glory_077", category: "Grit & Glory", text: "Your body is not the enemy; it is the ally that needs consistent leadership." },
  { id: "grit_glory_078", category: "Grit & Glory", text: "You'll stop underestimating yourself the day you stop quitting early." },
  { id: "grit_glory_079", category: "Grit & Glory", text: "No one can gift you resilience; you must forge it under load." },
  { id: "grit_glory_080", category: "Grit & Glory", text: "Progress is often invisible until the day it suddenly isn't." },
  { id: "grit_glory_081", category: "Grit & Glory", text: "You can't control whether it's a \"good day\"—you can control if it's a day you trained." },
  { id: "grit_glory_082", category: "Grit & Glory", text: "You are allowed to take breaks; just don't make them your new personality." },
  { id: "grit_glory_083", category: "Grit & Glory", text: "Act like someone who respects the gift of having a body that can still move." },
  { id: "grit_glory_084", category: "Grit & Glory", text: "Treat your reps as if your children will inherit your discipline." },
  { id: "grit_glory_085", category: "Grit & Glory", text: "Your goals are not distant; they're stacked in the sets you skip or complete." },
  { id: "grit_glory_086", category: "Grit & Glory", text: "There is a quiet kind of glory in doing the right thing when nobody will know." },
  { id: "grit_glory_087", category: "Grit & Glory", text: "You're not \"starting over\"—you're starting wiser, and that changes everything." },
  { id: "grit_glory_088", category: "Grit & Glory", text: "The iron does not care about your past. It only responds to what you lift today." },
  { id: "grit_glory_089", category: "Grit & Glory", text: "The work never gets easier; you simply grow into someone it can't intimidate." },
  { id: "grit_glory_090", category: "Grit & Glory", text: "Show up especially on the days your mind invents the best reasons not to." },
  { id: "grit_glory_091", category: "Grit & Glory", text: "You are building a life where \"I don't feel like it\" no longer gets a vote." },
  { id: "grit_glory_092", category: "Grit & Glory", text: "Remember why you started, then train like you never want to go back." },
  { id: "grit_glory_093", category: "Grit & Glory", text: "Pain that comes from growth is a different species than pain that comes from avoidance." },
  { id: "grit_glory_094", category: "Grit & Glory", text: "One hard hour in the gym can silence a full day of self-doubt." },
  { id: "grit_glory_095", category: "Grit & Glory", text: "There is no hack that replaces time under tension." },
  { id: "grit_glory_096", category: "Grit & Glory", text: "You either make time for training or you make peace with shrinking." },
  { id: "grit_glory_097", category: "Grit & Glory", text: "Let the soreness remind you that you showed up when you could have checked out." },
  { id: "grit_glory_098", category: "Grit & Glory", text: "Stop romanticizing the idea of change and start romanticizing the act of effort." },
  { id: "grit_glory_099", category: "Grit & Glory", text: "Your greatest flex will always be self-mastery." },
  { id: "grit_glory_100", category: "Grit & Glory", text: "Treat every set like a small rebellion against the version of you that settles." },
  { id: "grit_glory_101", category: "Grit & Glory", text: "You are not chasing aesthetics; you are building an instrument for your mission." },
  { id: "grit_glory_102", category: "Grit & Glory", text: "There will never be a perfect time. There will always be a next rep." },
  { id: "grit_glory_103", category: "Grit & Glory", text: "You can train angry, tired, or unsure. You just can't train absent." },
  { id: "grit_glory_104", category: "Grit & Glory", text: "The gym is the altar where procrastination is sacrificed one set at a time." },
  { id: "grit_glory_105", category: "Grit & Glory", text: "Every session you finish is another reason to trust yourself." },
  { id: "grit_glory_106", category: "Grit & Glory", text: "Grit is the art of staying when your comfort has already left the building." },
  { id: "grit_glory_107", category: "Grit & Glory", text: "The day you stop giving up on yourself mid-set is the day everything else changes." },
  { id: "grit_glory_108", category: "Grit & Glory", text: "Glory is not found on the podium; it's found in the thousand quiet choices to keep going." }
];

export const sanctifiedFireQuotes: StockQuote[] = [
  { id: "sanctified_fire_001", category: "Sanctified Fire", text: "The same Jesus who calmed the sea can calm the storm inside your chest." },
  { id: "sanctified_fire_002", category: "Sanctified Fire", text: "Grace does not ask if you are worthy; it arrives because He is." },
  { id: "sanctified_fire_003", category: "Sanctified Fire", text: "You are not holding your life together; the pierced Hands are." },
  { id: "sanctified_fire_004", category: "Sanctified Fire", text: "When you ran from God, His mercy ran faster." },
  { id: "sanctified_fire_005", category: "Sanctified Fire", text: "The cross is not proof that you are terrible; it is proof that you are treasured." },
  { id: "sanctified_fire_006", category: "Sanctified Fire", text: "Jesus does not love the future, improved version of you more than the one breathing now." },
  { id: "sanctified_fire_007", category: "Sanctified Fire", text: "God is not surprised by the battle you are in; He prepared armor with your name on it." },
  { id: "sanctified_fire_008", category: "Sanctified Fire", text: "Hell keeps receipts of your failures. Heaven keeps records of His blood." },
  { id: "sanctified_fire_009", category: "Sanctified Fire", text: "Your weakness is not an interruption to God's plan; it is material for His glory." },
  { id: "sanctified_fire_010", category: "Sanctified Fire", text: "The Lion of Judah can roar over a heart that only manages a whisper of faith." },
  { id: "sanctified_fire_011", category: "Sanctified Fire", text: "Every breath you pray in the dark is already echoing in the throne room." },
  { id: "sanctified_fire_012", category: "Sanctified Fire", text: "God is not counting how many times you fell; He is helping you stand up one more time." },
  { id: "sanctified_fire_013", category: "Sanctified Fire", text: "Your anxiety has loud facts, but His promises are louder truth." },
  { id: "sanctified_fire_014", category: "Sanctified Fire", text: "The tomb is still empty; that means hope is still full." },
  { id: "sanctified_fire_015", category: "Sanctified Fire", text: "You are not walking toward God when you pray; you are answering the One already near." },
  { id: "sanctified_fire_016", category: "Sanctified Fire", text: "God can use even the chapters you regret as pages in someone else's healing." },
  { id: "sanctified_fire_017", category: "Sanctified Fire", text: "You are not an accident wandering toward purpose; you are a purpose walking through time." },
  { id: "sanctified_fire_018", category: "Sanctified Fire", text: "Jesus sits with you in the place you are ashamed to invite anyone else into." },
  { id: "sanctified_fire_019", category: "Sanctified Fire", text: "The blood of Christ does not fade with repetition; it is eternally fresh over your name." },
  { id: "sanctified_fire_020", category: "Sanctified Fire", text: "You are not too broken to be used; you are perfectly positioned to show His mending." },
  { id: "sanctified_fire_021", category: "Sanctified Fire", text: "God's timing is not late; it simply arrives when surrender has prepared your hands." },
  { id: "sanctified_fire_022", category: "Sanctified Fire", text: "Your secret tears have a public Advocate." },
  { id: "sanctified_fire_023", category: "Sanctified Fire", text: "The Shepherd never loses count of the one who wanders." },
  { id: "sanctified_fire_024", category: "Sanctified Fire", text: "You are not striving to earn sonship; you are learning to live like the child you already are." },
  { id: "sanctified_fire_025", category: "Sanctified Fire", text: "The Holy Spirit does not shame you into change; He loves you into transformation." },
  { id: "sanctified_fire_026", category: "Sanctified Fire", text: "Some battles are not for you to win, but for you to watch God fight while you worship." },
  { id: "sanctified_fire_027", category: "Sanctified Fire", text: "You are not praying into a void; you are knocking on a door already opened by nail scars." },
  { id: "sanctified_fire_028", category: "Sanctified Fire", text: "Every scar on Christ's body is a receipt that your debt is paid in full." },
  { id: "sanctified_fire_029", category: "Sanctified Fire", text: "Your calling does not depend on the approval of those who do not hear God's voice over you." },
  { id: "sanctified_fire_030", category: "Sanctified Fire", text: "When you say, \"I can't go on,\" Heaven answers, \"You don't have to go alone.\"" },
  { id: "sanctified_fire_031", category: "Sanctified Fire", text: "Holiness is not a performance; it is staying close enough to God that His heart rubs off on yours." },
  { id: "sanctified_fire_032", category: "Sanctified Fire", text: "Your worship in weakness weighs more than your pride in strength." },
  { id: "sanctified_fire_033", category: "Sanctified Fire", text: "The Lord doesn't just restore what you lost; He restores what you became while losing it." },
  { id: "sanctified_fire_034", category: "Sanctified Fire", text: "You will never find a place God cannot reach, because He arrived there before your fall." },
  { id: "sanctified_fire_035", category: "Sanctified Fire", text: "Conviction says, \"Come home.\" Condemnation says, \"Stay gone.\" Learn which voice is Christ's." },
  { id: "sanctified_fire_036", category: "Sanctified Fire", text: "You cannot out-sin the patience of the One who died knowing every chapter in advance." },
  { id: "sanctified_fire_037", category: "Sanctified Fire", text: "The same Spirit that raised Jesus from the dead is not intimidated by your bad habits." },
  { id: "sanctified_fire_038", category: "Sanctified Fire", text: "God can turn your \"Why me?\" into \"Use me.\"" },
  { id: "sanctified_fire_039", category: "Sanctified Fire", text: "Your past is a place of reference, not residence." },
  { id: "sanctified_fire_040", category: "Sanctified Fire", text: "Jesus did not come to make bad people good; He came to make dead people alive." },
  { id: "sanctified_fire_041", category: "Sanctified Fire", text: "You are not a project for God to fix; you are a beloved one He delights to walk with." },
  { id: "sanctified_fire_042", category: "Sanctified Fire", text: "Your hidden obedience is loud worship in Heaven." },
  { id: "sanctified_fire_043", category: "Sanctified Fire", text: "The valley you fear is already mapped by a Shepherd who carries both rod and staff." },
  { id: "sanctified_fire_044", category: "Sanctified Fire", text: "Every time you forgive, you look a little more like the One who forgave you first." },
  { id: "sanctified_fire_045", category: "Sanctified Fire", text: "Your identity is not \"the one who failed\"; it is \"the one He rescued.\"" },
  { id: "sanctified_fire_046", category: "Sanctified Fire", text: "God does not just see the giant before you; He sees the worship after it falls." },
  { id: "sanctified_fire_047", category: "Sanctified Fire", text: "You did not miss God's will because of one wrong turn; His mercy is better at rerouting than your fear is at driving." },
  { id: "sanctified_fire_048", category: "Sanctified Fire", text: "Christ did not call perfect disciples, only willing ones." },
  { id: "sanctified_fire_049", category: "Sanctified Fire", text: "The same hands that stretched out on the cross are stretched toward you every ordinary morning." },
  { id: "sanctified_fire_050", category: "Sanctified Fire", text: "Your prayers are not powerful because of your words but because of the Name attached to them." },
  { id: "sanctified_fire_051", category: "Sanctified Fire", text: "God is not disappointed that you need Him; He is delighted that you came." },
  { id: "sanctified_fire_052", category: "Sanctified Fire", text: "The devil reminds you of your history; God reminds you of the cross." },
  { id: "sanctified_fire_053", category: "Sanctified Fire", text: "Your broken \"Hallelujah\" is still a Hallelujah." },
  { id: "sanctified_fire_054", category: "Sanctified Fire", text: "Heaven is not impressed with polished religion but moved by honest surrender." },
  { id: "sanctified_fire_055", category: "Sanctified Fire", text: "When you feel unseen, remember the One who numbers your hairs also bottles your tears." },
  { id: "sanctified_fire_056", category: "Sanctified Fire", text: "Your calling is not to be famous; it is to be faithful." },
  { id: "sanctified_fire_057", category: "Sanctified Fire", text: "God often hides His greatest work in seasons that feel like silence." },
  { id: "sanctified_fire_058", category: "Sanctified Fire", text: "You can rest because the universe does not depend on your constant vigilance; it rests on His word." },
  { id: "sanctified_fire_059", category: "Sanctified Fire", text: "Christ is not asking you to carry the cross alone; He is asking you to walk with the One who already carried it." },
  { id: "sanctified_fire_060", category: "Sanctified Fire", text: "The Holy Spirit is not a distant force; He is a present Friend." },
  { id: "sanctified_fire_061", category: "Sanctified Fire", text: "You do not fight for victory; you fight from it." },
  { id: "sanctified_fire_062", category: "Sanctified Fire", text: "Your doubts do not scare Jesus; He walked through locked doors to meet a doubter." },
  { id: "sanctified_fire_063", category: "Sanctified Fire", text: "Sometimes God calms the storm; sometimes He calms the child and lets the storm roar." },
  { id: "sanctified_fire_064", category: "Sanctified Fire", text: "You cannot embarrass God with your honesty; He already knows and still invites." },
  { id: "sanctified_fire_065", category: "Sanctified Fire", text: "The light of Christ reaches corners your self-hatred never told you existed." },
  { id: "sanctified_fire_066", category: "Sanctified Fire", text: "Your story is not over while resurrection power is in the script." },
  { id: "sanctified_fire_067", category: "Sanctified Fire", text: "Obedience may look small on earth but it is huge on Heaven's scoreboard." },
  { id: "sanctified_fire_068", category: "Sanctified Fire", text: "God does not love you less on the days you feel numb." },
  { id: "sanctified_fire_069", category: "Sanctified Fire", text: "The presence of fear does not mean the absence of faith; it means faith has something to do." },
  { id: "sanctified_fire_070", category: "Sanctified Fire", text: "Jesus carries both your shame and your future in the same gentle hands." },
  { id: "sanctified_fire_071", category: "Sanctified Fire", text: "Your worship is not a playlist; it is every choice you make in the sight of God." },
  { id: "sanctified_fire_072", category: "Sanctified Fire", text: "The kingdom is not built on your perfection but on His." },
  { id: "sanctified_fire_073", category: "Sanctified Fire", text: "Heaven does not weigh you by your productivity but by your proximity." },
  { id: "sanctified_fire_074", category: "Sanctified Fire", text: "Even when you feel stuck, God is not stuck planning goodness over you." },
  { id: "sanctified_fire_075", category: "Sanctified Fire", text: "The shadow you fear cannot exist without the light that creates it." },
  { id: "sanctified_fire_076", category: "Sanctified Fire", text: "Your love for Jesus may flicker; His love for you does not." },
  { id: "sanctified_fire_077", category: "Sanctified Fire", text: "Christ is more committed to your transformation than you are afraid of your failure." },
  { id: "sanctified_fire_078", category: "Sanctified Fire", text: "You cannot scare away the Good Shepherd by limping." },
  { id: "sanctified_fire_079", category: "Sanctified Fire", text: "The love that found you will not suddenly misplace you." },
  { id: "sanctified_fire_080", category: "Sanctified Fire", text: "Your life is a letter Christ is writing to someone who needs hope." },
  { id: "sanctified_fire_081", category: "Sanctified Fire", text: "Sometimes the holiest thing you can do is breathe and remember who holds you." },
  { id: "sanctified_fire_082", category: "Sanctified Fire", text: "You cannot disappoint a God who knew everything and still chose you." },
  { id: "sanctified_fire_083", category: "Sanctified Fire", text: "The same God who flung galaxies listens when you whisper, \"Help.\"" },
  { id: "sanctified_fire_084", category: "Sanctified Fire", text: "Christ does not love a future 'fixed' version of your family; He loves the real one now." },
  { id: "sanctified_fire_085", category: "Sanctified Fire", text: "You are seated with Christ in heavenly places, even when your feelings are on the floor." },
  { id: "sanctified_fire_086", category: "Sanctified Fire", text: "Nothing you surrender to God is ever truly lost; it is replanted." },
  { id: "sanctified_fire_087", category: "Sanctified Fire", text: "The darkest chapter of your story can become the brightest testimony of His mercy." },
  { id: "sanctified_fire_088", category: "Sanctified Fire", text: "You are not too damaged to carry the presence of God; the ark has rested on rough wood before." },
  { id: "sanctified_fire_089", category: "Sanctified Fire", text: "When you don't know what to pray, the Name of Jesus is a whole prayer." },
  { id: "sanctified_fire_090", category: "Sanctified Fire", text: "The kingdom advances every time you choose love where revenge would be easier." },
  { id: "sanctified_fire_091", category: "Sanctified Fire", text: "God's mercy doesn't run on your battery level." },
  { id: "sanctified_fire_092", category: "Sanctified Fire", text: "The battle is not to prove your strength; it is to prove His faithfulness again." },
  { id: "sanctified_fire_093", category: "Sanctified Fire", text: "You are not what you lost; you are who He loved while you were losing it." },
  { id: "sanctified_fire_094", category: "Sanctified Fire", text: "Jesus is not only the way to Heaven; He is the way to being fully alive on earth." },
  { id: "sanctified_fire_095", category: "Sanctified Fire", text: "Your yes to God today echoes longer than your comfort tonight." },
  { id: "sanctified_fire_096", category: "Sanctified Fire", text: "The Spirit can make a throne out of a heart you once thought was rubble." },
  { id: "sanctified_fire_097", category: "Sanctified Fire", text: "You don't have to understand everything to trust the One who does." },
  { id: "sanctified_fire_098", category: "Sanctified Fire", text: "Every temptation is also an invitation to discover how strong God can be in you." },
  { id: "sanctified_fire_099", category: "Sanctified Fire", text: "Your story in Christ ends in redemption, even if today is a cliffhanger." },
  { id: "sanctified_fire_100", category: "Sanctified Fire", text: "You are not alone in the fire; there is always Another in the flames." },
  { id: "sanctified_fire_101", category: "Sanctified Fire", text: "Heaven is more real than the fear that keeps you awake at night." },
  { id: "sanctified_fire_102", category: "Sanctified Fire", text: "The voice that called Lazarus out of the grave is calling your hope out too." },
  { id: "sanctified_fire_103", category: "Sanctified Fire", text: "You are not tolerated in the kingdom; you are celebrated." },
  { id: "sanctified_fire_104", category: "Sanctified Fire", text: "The cross is God's forever \"I love you\" written in a language every heart understands." },
  { id: "sanctified_fire_105", category: "Sanctified Fire", text: "You will never regret the obedience you gave Jesus; only the time you delayed it." },
  { id: "sanctified_fire_106", category: "Sanctified Fire", text: "Your life is safest when it is most surrendered." },
  { id: "sanctified_fire_107", category: "Sanctified Fire", text: "Nothing can separate you from the love of Christ; not even the parts of you you don't like." },
  { id: "sanctified_fire_108", category: "Sanctified Fire", text: "The fire of God does not burn you up; it burns away everything that is not really you." }
];

export const visionQuestQuotes: StockQuote[] = [
  { id: "vision_quest_001", category: "Vision Quest", text: "A child followed a firefly into the forest and found a hidden library inside an oak. Every book was blank until she opened it; then her next brave decision appeared on the page." },
  { id: "vision_quest_002", category: "Vision Quest", text: "A warrior laid down his sword beside a river of stars and discovered it was his own reflection that had been attacking him all along." },
  { id: "vision_quest_003", category: "Vision Quest", text: "In a city where clocks ruled every decision, one tower forgot how to tick. People gathered beneath it and, for the first time, remembered how to breathe." },
  { id: "vision_quest_004", category: "Vision Quest", text: "On the edge of the world, a girl painted doors on canyon walls. Some laughed, but those who knocked found whole universes answering." },
  { id: "vision_quest_005", category: "Vision Quest", text: "A wandering monk carried an invisible lantern. It never lit his path, only the faces of those he chose to listen to." },
  { id: "vision_quest_006", category: "Vision Quest", text: "A dragon grew tired of guarding gold no one touched. One day it curled around a village instead, and the people slept without fear for the first time in generations." },
  { id: "vision_quest_007", category: "Vision Quest", text: "A kingdom trapped its nightmares in glass bottles. When a child shattered one, they discovered the monster simply needed a name and a hug." },
  { id: "vision_quest_008", category: "Vision Quest", text: "At the bottom of an old well, a boy found the sky—perfectly reflected. He realized he had never been far from heaven, only looking in the wrong direction." },
  { id: "vision_quest_009", category: "Vision Quest", text: "An old wolf refused the hunt and started telling stories instead. The pack grew kinder, but their teeth grew sharper against lies." },
  { id: "vision_quest_010", category: "Vision Quest", text: "A village hired an architect to build a wall around their hearts. She built windows instead and apologized for misunderstanding on purpose." },
  { id: "vision_quest_011", category: "Vision Quest", text: "A sailor chased the horizon until his map burned away. Only then did he notice the constellations spelling out his real name." },
  { id: "vision_quest_012", category: "Vision Quest", text: "There was a forest where trees grew according to the secrets whispered beneath them. One tree towered above the rest: it had heard the confession, \"I am afraid, but I will love anyway.\"" },
  { id: "vision_quest_013", category: "Vision Quest", text: "A city floated in the clouds, tethered by chains of fear. A single honest conversation snapped the first link." },
  { id: "vision_quest_014", category: "Vision Quest", text: "A scholar devoted his life to studying light. When he finally met it, it asked only one question: \"Who have you warmed?\"" },
  { id: "vision_quest_015", category: "Vision Quest", text: "A mirror refused to show appearances. Instead, it revealed the one decision each person was avoiding." },
  { id: "vision_quest_016", category: "Vision Quest", text: "In a desert of abandoned dreams, one seed sprouted where someone whispered, \"Even now.\"" },
  { id: "vision_quest_017", category: "Vision Quest", text: "A knight removed his armor and found he could finally hear the birds blessing his scars." },
  { id: "vision_quest_018", category: "Vision Quest", text: "A comet asked the Creator why it burned so briefly. \"Because,\" came the answer, \"some hearts will only look up once.\"" },
  { id: "vision_quest_019", category: "Vision Quest", text: "In a kingdom where everyone wore crowns, one woman set hers down and started washing feet. The ground itself began to glow where she walked." },
  { id: "vision_quest_020", category: "Vision Quest", text: "A musician lost his hearing but kept playing. Heaven leaned closer, thrilled to finally hear the song underneath the notes." },
  { id: "vision_quest_021", category: "Vision Quest", text: "At the center of a maze, there was no treasure—only a quiet bench and a note: \"Sit. The labyrinth was inside you the whole time.\"" },
  { id: "vision_quest_022", category: "Vision Quest", text: "A phoenix refused to rise after burning. Instead, it spread its ashes over a field and watched a thousand flowers learn resurrection." },
  { id: "vision_quest_023", category: "Vision Quest", text: "In a land where people traded masks, one child sold theirs and bought a lantern instead." },
  { id: "vision_quest_024", category: "Vision Quest", text: "A monastery kept its gates locked for centuries. When they finally opened them, they discovered the world outside had quietly become the sanctuary." },
  { id: "vision_quest_025", category: "Vision Quest", text: "A constellation rearranged itself each night to match the questions of a single, restless soul." },
  { id: "vision_quest_026", category: "Vision Quest", text: "A city of stone statues waited for a prophecy to free them. It turned out the prophecy was simply, \"Feel.\"" },
  { id: "vision_quest_027", category: "Vision Quest", text: "A girl found a door in her chest that only opened when she forgave herself." },
  { id: "vision_quest_028", category: "Vision Quest", text: "A librarian guarded a forbidden shelf that contained only one book: the story of who you would be if you believed you were loved." },
  { id: "vision_quest_029", category: "Vision Quest", text: "An ocean asked a grain of sand what it feared. \"Being forgotten,\" it replied. The ocean smiled and said, \"I carry you in every wave.\"" },
  { id: "vision_quest_030", category: "Vision Quest", text: "A boy climbed a mountain to ask the hermit how to find peace. The hermit handed him a mirror and a broom." },
  { id: "vision_quest_031", category: "Vision Quest", text: "A goddess hid her throne inside a mother's lap. Only children recognized her crown." },
  { id: "vision_quest_032", category: "Vision Quest", text: "In a realm of endless noise, an oracle spoke only once a year. Her message was always the same: \"Listen to the quiet person in the room.\"" },
  { id: "vision_quest_033", category: "Vision Quest", text: "A swordsmith forged a blade so honest it shattered whenever someone lied while holding it. Eventually, people learned to speak carefully instead." },
  { id: "vision_quest_034", category: "Vision Quest", text: "A door appeared in the sky above a battlefield. It led to a room where both sides were children, sharing crayons." },
  { id: "vision_quest_035", category: "Vision Quest", text: "A time traveler tried to fix their worst mistake, only to discover their healing in the present changed the past more safely than any machine." },
  { id: "vision_quest_036", category: "Vision Quest", text: "A monastery kept a single, forbidden question in a locked chest. When opened, the parchment read, \"What if you are already forgiven?\"" },
  { id: "vision_quest_037", category: "Vision Quest", text: "A child's bedtime prayer held together a planet that scientists swore was doomed." },
  { id: "vision_quest_038", category: "Vision Quest", text: "A celestial scribe wrote destinies in ink made of tears. The brightest stories began where someone wept but did not quit." },
  { id: "vision_quest_039", category: "Vision Quest", text: "A kingdom outlawed shadows, but the sun refused to participate." },
  { id: "vision_quest_040", category: "Vision Quest", text: "A pilgrim carried a heavy stone for miles, thinking it was his punishment. At the mountaintop, he found it was the cornerstone of his new home." },
  { id: "vision_quest_041", category: "Vision Quest", text: "A star fell into a river and became a lantern for fishermen who didn't know they were angels on night shift." },
  { id: "vision_quest_042", category: "Vision Quest", text: "A girl befriended the monster under her bed and discovered it was only there to eat her unspoken fears." },
  { id: "vision_quest_043", category: "Vision Quest", text: "In a museum of broken promises, one exhibit kept repairing itself every morning. No one realized it was curated by mercy." },
  { id: "vision_quest_044", category: "Vision Quest", text: "A map with no lines showed only a glowing dot and three words: \"You are here.\" It was enough." },
  { id: "vision_quest_045", category: "Vision Quest", text: "A river refused to freeze, even in the harshest winter. When asked why, it answered, \"I remember the Source.\"" },
  { id: "vision_quest_046", category: "Vision Quest", text: "A tower of ivory cracked the day a single honest prayer rose higher than its spire." },
  { id: "vision_quest_047", category: "Vision Quest", text: "A boy met his future self in a dream and was disappointed to see the same eyes. The future self smiled and said, \"That means we kept our soul.\"" },
  { id: "vision_quest_048", category: "Vision Quest", text: "A queen removed the jewels from her crown and planted them in the soil. They grew into trees that bore fruits of second chances." },
  { id: "vision_quest_049", category: "Vision Quest", text: "In a realm where names were bought and sold, one person chose to be called \"Here\" and finally arrived." },
  { id: "vision_quest_050", category: "Vision Quest", text: "A lantern in the temple refused oil unless someone lit another's candle first." },
  { id: "vision_quest_051", category: "Vision Quest", text: "A boy collected insults in a glass jar until one day they turned into seeds and he realized he could choose where to bury them." },
  { id: "vision_quest_052", category: "Vision Quest", text: "A city's river ran backward for one hour each year, carrying regrets upstream so people could decide again." },
  { id: "vision_quest_053", category: "Vision Quest", text: "Two souls met in a dream and recognized each other by the way they held their wounds gently." },
  { id: "vision_quest_054", category: "Vision Quest", text: "In the final room of the universe, the Creator kept a single chair—for you—and a question: \"What did you learn about love?\"" }
];

export const christwardFlameQuotes: StockQuote[] = [
  { id: "christward_flame_001", category: "Christward Flame", text: "Jesus is not just part of your story; He is the One who turns every page with you." },
  { id: "christward_flame_002", category: "Christward Flame", text: "The cross is proof that God would rather suffer for you than live without you." },
  { id: "christward_flame_003", category: "Christward Flame", text: "You are not holding yourself together; His grace is quietly doing that every hour." },
  { id: "christward_flame_004", category: "Christward Flame", text: "When you feel unworthy to pray, remember He already died knowing every prayer you would ever need." },
  { id: "christward_flame_005", category: "Christward Flame", text: "Your weakness is not a surprise to Jesus; it is the very place He planned to pour His strength." },
  { id: "christward_flame_006", category: "Christward Flame", text: "The Shepherd does not love the sheep more when they walk straight; He loves them because they are His." },
  { id: "christward_flame_007", category: "Christward Flame", text: "Every time you whisper His Name, the King of Heaven inclines His ear like a Friend on the couch beside you." },
  { id: "christward_flame_008", category: "Christward Flame", text: "Jesus is not intimidated by the mess in your heart; He moved into a manger to prove it." },
  { id: "christward_flame_009", category: "Christward Flame", text: "Grace means you are more than the worst thing you have done and more than the best thing you can boast." },
  { id: "christward_flame_010", category: "Christward Flame", text: "When you ran away, He did not stay seated on the throne; He ran down the road to meet you." },
  { id: "christward_flame_011", category: "Christward Flame", text: "The hands that made galaxies also washed feet. That is the kind of Lord who holds you." },
  { id: "christward_flame_012", category: "Christward Flame", text: "Jesus never asked you to impress Him; He asked you to follow Him." },
  { id: "christward_flame_013", category: "Christward Flame", text: "You cannot out-sin the cross, but you can out-stubborn the embrace. Sooner or later, let yourself be held." },
  { id: "christward_flame_014", category: "Christward Flame", text: "He does not love a future, cleaned-up version of you; He loves the breathing soul in front of Him right now." },
  { id: "christward_flame_015", category: "Christward Flame", text: "The Good Shepherd does not count your failures; He counts your steps back home." },
  { id: "christward_flame_016", category: "Christward Flame", text: "Every wound He received was a doorway for you to walk deeper into the Father's heart." },
  { id: "christward_flame_017", category: "Christward Flame", text: "Faith is not pretending everything is fine; faith is bringing the not-fine straight to Jesus." },
  { id: "christward_flame_018", category: "Christward Flame", text: "Your prayers are not lost in the ceiling; they are stored like incense in the throne room of God." },
  { id: "christward_flame_019", category: "Christward Flame", text: "Jesus did not come to make you slightly improved; He came to make you radically alive." },
  { id: "christward_flame_020", category: "Christward Flame", text: "The nails that pierced Him did not nail you to shame; they nailed your shame to the past." },
  { id: "christward_flame_021", category: "Christward Flame", text: "He knows every chapter of your story and still chose to sign His Name on the cover." },
  { id: "christward_flame_022", category: "Christward Flame", text: "Even when you cannot feel His presence, His promise is still wrapped around your breath." },
  { id: "christward_flame_023", category: "Christward Flame", text: "Jesus is not your Plan B; He is the foundation under every possible plan." },
  { id: "christward_flame_024", category: "Christward Flame", text: "The same voice that calmed the sea can calm the arguments inside your chest." },
  { id: "christward_flame_025", category: "Christward Flame", text: "Your doubts don't scare Him; one honest \"help my unbelief\" is a prayer He treasures." },
  { id: "christward_flame_026", category: "Christward Flame", text: "He walked into death so that death would never again be able to lock the door on you." },
  { id: "christward_flame_027", category: "Christward Flame", text: "You are not chasing a distant Savior; you are walking with a Friend who already knows the way home." },
  { id: "christward_flame_028", category: "Christward Flame", text: "Every time you choose mercy instead of revenge, you look a little more like the One you follow." },
  { id: "christward_flame_029", category: "Christward Flame", text: "Your failures are not the headline of Heaven; the headline is always: \"My grace is sufficient.\"" },
  { id: "christward_flame_030", category: "Christward Flame", text: "He did not call you because you were ready; He called you because His love is." },
  { id: "christward_flame_031", category: "Christward Flame", text: "The closer you get to Jesus, the less you need the applause of the crowd." },
  { id: "christward_flame_032", category: "Christward Flame", text: "If all you can pray today is \"Jesus, hold me,\" Heaven calls that a complete sentence." },
  { id: "christward_flame_033", category: "Christward Flame", text: "He knows the exact weight of what you carry and refuses to walk one step away from you." },
  { id: "christward_flame_034", category: "Christward Flame", text: "Holiness is not cold distance; it is burning love that refuses to leave you where it found you." },
  { id: "christward_flame_035", category: "Christward Flame", text: "When you feel like you've ruined everything, remember the cross was prepared for exactly that fear." },
  { id: "christward_flame_036", category: "Christward Flame", text: "Jesus does not measure you by your last breakdown but by His last \"It is finished.\"" },
  { id: "christward_flame_037", category: "Christward Flame", text: "He is not asking you to fix yourself; He is asking you to stay near while He heals you." },
  { id: "christward_flame_038", category: "Christward Flame", text: "Every secret tear you've cried in the dark has already been counted in His light." },
  { id: "christward_flame_039", category: "Christward Flame", text: "You are not an interruption to Jesus; you are the reason He keeps stopping for people on the road." },
  { id: "christward_flame_040", category: "Christward Flame", text: "The kingdom is not built by perfect people, but by forgiven ones who keep saying yes." },
  { id: "christward_flame_041", category: "Christward Flame", text: "He calls you \"beloved\" on the days you feel like a burden." },
  { id: "christward_flame_042", category: "Christward Flame", text: "Your anxiety may be loud, but His \"Do not fear, I am with you\" is the deeper soundtrack." },
  { id: "christward_flame_043", category: "Christward Flame", text: "The cross was not a transaction only; it was a declaration: \"I choose you forever.\"" },
  { id: "christward_flame_044", category: "Christward Flame", text: "You don't have to climb up to God; He already climbed down into your humanity." },
  { id: "christward_flame_045", category: "Christward Flame", text: "Even when you feel numb, the Spirit is still interceding with groans too deep for words." },
  { id: "christward_flame_046", category: "Christward Flame", text: "The One who calmed the storm outside the boat can calm the one inside your mind." },
  { id: "christward_flame_047", category: "Christward Flame", text: "He does not merely repair broken hearts; He lives inside them." },
  { id: "christward_flame_048", category: "Christward Flame", text: "You cannot disappoint a God who knew your whole story and still chose a cross." },
  { id: "christward_flame_049", category: "Christward Flame", text: "Every time you choose forgiveness, you join Jesus in breaking chains you cannot see." },
  { id: "christward_flame_050", category: "Christward Flame", text: "Your calling is not to be famous; your calling is to be faithful to the One who loves you." },
  { id: "christward_flame_051", category: "Christward Flame", text: "He sees the battle in your thoughts, and He is not ashamed to call you His own in the middle of it." },
  { id: "christward_flame_052", category: "Christward Flame", text: "The blood of Jesus speaks a louder word over you than any accusation ever will." },
  { id: "christward_flame_053", category: "Christward Flame", text: "When you fall again, He does not roll His eyes; He offers His hand." },
  { id: "christward_flame_054", category: "Christward Flame", text: "You are not approaching a throne of judgment; you are running to a throne of grace." },
  { id: "christward_flame_055", category: "Christward Flame", text: "The gospel is not \"try harder\"; the gospel is \"it is finished,\" now walk with Me." },
  { id: "christward_flame_056", category: "Christward Flame", text: "He is closer than your pulse and yet grander than all the galaxies combined." },
  { id: "christward_flame_057", category: "Christward Flame", text: "Even your most tangled season can become a testimony when placed in His hands." },
  { id: "christward_flame_058", category: "Christward Flame", text: "Jesus is not a chapter in your life; He is the author, the ink, and the breath between every line." },
  { id: "christward_flame_059", category: "Christward Flame", text: "You don't carry the world on your shoulders; you carry a cross-shaped reminder that He already did." },
  { id: "christward_flame_060", category: "Christward Flame", text: "You are allowed to be honest with God; He already knows the words you're afraid to say." },
  { id: "christward_flame_061", category: "Christward Flame", text: "The Lamb who was slain now roars like a Lion over your destiny." },
  { id: "christward_flame_062", category: "Christward Flame", text: "Nothing you confess will ever shock the One who hung naked on a cross for you." },
  { id: "christward_flame_063", category: "Christward Flame", text: "Every time you love someone hard to love, you preach a silent sermon with your life." },
  { id: "christward_flame_064", category: "Christward Flame", text: "Your past is a place of reference, not residence; the Spirit is guiding you forward." },
  { id: "christward_flame_065", category: "Christward Flame", text: "He does not just forgive you; He delights in you." },
  { id: "christward_flame_066", category: "Christward Flame", text: "The closer you walk with Jesus, the less afraid you become of running out of love." },
  { id: "christward_flame_067", category: "Christward Flame", text: "Your obedience will never earn His love, but His love will always empower your obedience." },
  { id: "christward_flame_068", category: "Christward Flame", text: "When you carry your cross, remember you are walking behind Someone who carried it first." },
  { id: "christward_flame_069", category: "Christward Flame", text: "You are not stuck; you are held while He rearranges what you cannot yet see." },
  { id: "christward_flame_070", category: "Christward Flame", text: "The greatest ministry you have is not your platform; it is the way you love like Christ when no one is watching." },
  { id: "christward_flame_071", category: "Christward Flame", text: "His mercy runs faster than your mistakes." },
  { id: "christward_flame_072", category: "Christward Flame", text: "Every \"impossible\" in your life is already measured against an empty tomb." },
  { id: "christward_flame_073", category: "Christward Flame", text: "You are not praying to get His attention; you are praying because you already have it." },
  { id: "christward_flame_074", category: "Christward Flame", text: "The Spirit is not a distant force; He is the breath of Christ inside your chest." },
  { id: "christward_flame_075", category: "Christward Flame", text: "You don't have to understand everything to trust the One who understands you." },
  { id: "christward_flame_076", category: "Christward Flame", text: "He sat at tables with the broken so that you would never think you had to eat alone in your shame." },
  { id: "christward_flame_077", category: "Christward Flame", text: "Your identity is not \"the one who failed\"; your identity is \"the one He loves.\"" },
  { id: "christward_flame_078", category: "Christward Flame", text: "The cross is God saying, \"I know exactly how dark it can get, and I am still here.\"" },
  { id: "christward_flame_079", category: "Christward Flame", text: "Every small yes to Jesus is a crack in the walls around your heart where light gets in." },
  { id: "christward_flame_080", category: "Christward Flame", text: "Your story in Christ does not end in shame, defeat, or emptiness; it ends in resurrection." },
  { id: "christward_flame_081", category: "Christward Flame", text: "Jesus did not come to make religious professionals; He came to make sons and daughters at home with the Father." },
  { id: "christward_flame_082", category: "Christward Flame", text: "The more you stare at His love, the less power your fear has to narrate your future." },
  { id: "christward_flame_083", category: "Christward Flame", text: "He turned water into wine to whisper, \"I can make joy out of what you think is ordinary.\"" },
  { id: "christward_flame_084", category: "Christward Flame", text: "You can bring your anger, confusion, and grief to Jesus; He has already carried them to the cross." },
  { id: "christward_flame_085", category: "Christward Flame", text: "You are not just saved from something; you are saved into a living, breathing relationship with Him." },
  { id: "christward_flame_086", category: "Christward Flame", text: "Every breath you take is another chance to say, \"Here I am, Lord, still Yours.\"" },
  { id: "christward_flame_087", category: "Christward Flame", text: "He carried a cross so you would never again have to carry condemnation." },
  { id: "christward_flame_088", category: "Christward Flame", text: "Your life with Jesus is not a performance; it is a pilgrimage of being loved into wholeness." },
  { id: "christward_flame_089", category: "Christward Flame", text: "The same Christ who calmed storms and raised the dead is gentle with your trembling heart." },
  { id: "christward_flame_090", category: "Christward Flame", text: "Nothing can separate you from His love—not your past, not your present, not the storm you haven't seen yet." },
  { id: "christward_flame_091", category: "Christward Flame", text: "You don't need to earn forgiveness that was poured out before you ever asked for it." },
  { id: "christward_flame_092", category: "Christward Flame", text: "Let the cross be the loudest thing you hear when shame tries to preach at you." },
  { id: "christward_flame_093", category: "Christward Flame", text: "Every time you come back to Jesus, you are not restarting; you are going deeper." },
  { id: "christward_flame_094", category: "Christward Flame", text: "He turned His own grave into a doorway; trust Him with the dead places in your life." },
  { id: "christward_flame_095", category: "Christward Flame", text: "You are not a guest in God's house; you are family because of Christ." },
  { id: "christward_flame_096", category: "Christward Flame", text: "The world measures you by what you produce; Jesus measures you by whose you are." },
  { id: "christward_flame_097", category: "Christward Flame", text: "He knows the real you beneath every mask and still says, \"Follow Me.\"" },
  { id: "christward_flame_098", category: "Christward Flame", text: "Your heart is not too complicated for Christ; He understands the language of your sighs." },
  { id: "christward_flame_099", category: "Christward Flame", text: "You are loved on your worst day exactly as much as on your best one." },
  { id: "christward_flame_100", category: "Christward Flame", text: "Jesus does not just forgive your past; He walks into your future with you." },
  { id: "christward_flame_101", category: "Christward Flame", text: "Your secret prayers in the night are treated like treasure in His kingdom." },
  { id: "christward_flame_102", category: "Christward Flame", text: "The cross is where God shouted into history: \"I am for you, not against you.\"" },
  { id: "christward_flame_103", category: "Christward Flame", text: "No chain is safe around a heart that keeps calling on the Name of Jesus." },
  { id: "christward_flame_104", category: "Christward Flame", text: "Even when you cannot see the path, you can hold the hand of the One who is the Way." },
  { id: "christward_flame_105", category: "Christward Flame", text: "Your life is not random; it is being woven into a story where Christ is the faithful center." },
  { id: "christward_flame_106", category: "Christward Flame", text: "He knows how tired you are, and He still calls you \"my beloved,\" not \"my disappointment.\"" },
  { id: "christward_flame_107", category: "Christward Flame", text: "The love that found you will never again leave you orphaned." },
  { id: "christward_flame_108", category: "Christward Flame", text: "Jesus is not just the Savior of the world; He is the Lover of your one, irreplaceable soul." }
];

export const innerCitadelQuotes: StockQuote[] = [
  { "id": "inner_citadel_001", "category": "Inner Citadel", "text": "Your mind is a holy city. Do not hand its gates to every passing mood." },
  { "id": "inner_citadel_002", "category": "Inner Citadel", "text": "Peace is not found; it is defended, brick by brick, decision by decision." },
  { "id": "inner_citadel_003", "category": "Inner Citadel", "text": "Not every thought that knocks deserves a chair at your table." },
  { "id": "inner_citadel_004", "category": "Inner Citadel", "text": "Strength is not the absence of feeling; it is the refusal to be ruled by it." },
  { "id": "inner_citadel_005", "category": "Inner Citadel", "text": "If a voice would not dare speak in front of God, it has no right to speak over you." },
  { "id": "inner_citadel_006", "category": "Inner Citadel", "text": "You cannot stop the storm, but you can decide which winds are allowed inside." },
  { "id": "inner_citadel_007", "category": "Inner Citadel", "text": "Let your boundaries be like city walls: not cruel, just clearly built." },
  { "id": "inner_citadel_008", "category": "Inner Citadel", "text": "Every time you say no to what drains you, you say yes to what God is building in you." },
  { "id": "inner_citadel_009", "category": "Inner Citadel", "text": "Do not let temporary people write permanent sentences in your soul." },
  { "id": "inner_citadel_010", "category": "Inner Citadel", "text": "Silence is not weakness. It is often the armor of the wise." },
  { "id": "inner_citadel_011", "category": "Inner Citadel", "text": "You are responsible for what you dwell on, even if you are not responsible for what appears." },
  { "id": "inner_citadel_012", "category": "Inner Citadel", "text": "The throne of your heart is reserved for God. Do not let fear sit there." },
  { "id": "inner_citadel_013", "category": "Inner Citadel", "text": "When you master your response, you reclaim territory from everything that tried to own you." },
  { "id": "inner_citadel_014", "category": "Inner Citadel", "text": "You cannot control the story others tell about you, but you can live a life that contradicts it." },
  { "id": "inner_citadel_015", "category": "Inner Citadel", "text": "Guard your attention like treasure. Where it rests, your life leans." },
  { "id": "inner_citadel_016", "category": "Inner Citadel", "text": "Not every battle is yours. Choose the ones that grow your soul, not just your ego." },
  { "id": "inner_citadel_017", "category": "Inner Citadel", "text": "The loudest emotion is not always the truest one." },
  { "id": "inner_citadel_018", "category": "Inner Citadel", "text": "If a thought does not lead you toward love, truth, or courage, it is not worthy of meditation." },
  { "id": "inner_citadel_019", "category": "Inner Citadel", "text": "You are allowed to be kind and still close the gate." },
  { "id": "inner_citadel_020", "category": "Inner Citadel", "text": "Self-control is not about suppression; it is about stewardship." },
  { "id": "inner_citadel_021", "category": "Inner Citadel", "text": "Your peace is part of your assignment. Protect it like something sacred." },
  { "id": "inner_citadel_022", "category": "Inner Citadel", "text": "The person who can sit with their own discomfort without running owns a rare kind of power." },
  { "id": "inner_citadel_023", "category": "Inner Citadel", "text": "It is not cruel to step away from what is slowly destroying you." },
  { "id": "inner_citadel_024", "category": "Inner Citadel", "text": "What you repeat, you reinforce. Choose your inner sentences carefully." },
  { "id": "inner_citadel_025", "category": "Inner Citadel", "text": "Do not let people who refuse to heal be the loudest teachers in your mind." },
  { "id": "inner_citadel_026", "category": "Inner Citadel", "text": "Freedom grows where excuses die." },
  { "id": "inner_citadel_027", "category": "Inner Citadel", "text": "You are not obligated to attend every argument you are invited to." },
  { "id": "inner_citadel_028", "category": "Inner Citadel", "text": "Anger that is not guided by wisdom becomes a fire that burns its own house first." },
  { "id": "inner_citadel_029", "category": "Inner Citadel", "text": "Do not trade long-term peace for short-term validation." },
  { "id": "inner_citadel_030", "category": "Inner Citadel", "text": "You cannot heal in the same room that keeps rewarding your wounds." },
  { "id": "inner_citadel_031", "category": "Inner Citadel", "text": "Let God be the mirror you consult most; all others are cracked glass." },
  { "id": "inner_citadel_032", "category": "Inner Citadel", "text": "You may not control the first thought, but you decide whether it becomes a belief." },
  { "id": "inner_citadel_033", "category": "Inner Citadel", "text": "A quiet conscience is a softer pillow than any reputation." },
  { "id": "inner_citadel_034", "category": "Inner Citadel", "text": "Training your reaction is harder than training your body, and more important." },
  { "id": "inner_citadel_035", "category": "Inner Citadel", "text": "You owe no one constant access to you, only constant access to your integrity." },
  { "id": "inner_citadel_036", "category": "Inner Citadel", "text": "A boundary is love wearing armor." },
  { "id": "inner_citadel_037", "category": "Inner Citadel", "text": "The mind that kneels to God does not bow to chaos." },
  { "id": "inner_citadel_038", "category": "Inner Citadel", "text": "You are not rude for choosing silence where your spirit used to scream." },
  { "id": "inner_citadel_039", "category": "Inner Citadel", "text": "Slow down your tongue until your heart and wisdom can catch up." },
  { "id": "inner_citadel_040", "category": "Inner Citadel", "text": "Not everything broken inside you is your fault, but it is your responsibility now." },
  { "id": "inner_citadel_041", "category": "Inner Citadel", "text": "Do not give bitterness permanent residence where God planned a garden." },
  { "id": "inner_citadel_042", "category": "Inner Citadel", "text": "The one who rules their tongue can rule entire seasons of their life." },
  { "id": "inner_citadel_043", "category": "Inner Citadel", "text": "You are not cold for withdrawing from what continually harms you." },
  { "id": "inner_citadel_044", "category": "Inner Citadel", "text": "Let your standards be high enough that your soul can breathe." },
  { "id": "inner_citadel_045", "category": "Inner Citadel", "text": "A guarded heart is not a locked heart; it is a heart with discernment." },
  { "id": "inner_citadel_046", "category": "Inner Citadel", "text": "Every time you pause instead of reacting, another brick is added to your inner fortress." },
  { "id": "inner_citadel_047", "category": "Inner Citadel", "text": "Be loyal to your values, not to your impulses." },
  { "id": "inner_citadel_048", "category": "Inner Citadel", "text": "If peace costs you the approval of the restless, pay gladly." },
  { "id": "inner_citadel_049", "category": "Inner Citadel", "text": "The voice of God will never require you to betray the person you are becoming in Him." },
  { "id": "inner_citadel_050", "category": "Inner Citadel", "text": "The strongest person in the room is often the one least moved by the room." },
  { "id": "inner_citadel_051", "category": "Inner Citadel", "text": "Do not measure your worth by how much you endure from people who refuse to change." },
  { "id": "inner_citadel_052", "category": "Inner Citadel", "text": "Rehearsing old wounds is a form of self-harm. Lay them in God's hands instead." },
  { "id": "inner_citadel_053", "category": "Inner Citadel", "text": "You cannot force others to respect you, but you can refuse to join their disrespect." },
  { "id": "inner_citadel_054", "category": "Inner Citadel", "text": "Let your yes be wholehearted and your no be clean." },
  { "id": "inner_citadel_055", "category": "Inner Citadel", "text": "An unguarded mind will spend its days solving problems that don't exist." },
  { "id": "inner_citadel_056", "category": "Inner Citadel", "text": "Your triggers are invitations to build new walls of wisdom, not prisons of shame." },
  { "id": "inner_citadel_057", "category": "Inner Citadel", "text": "Some relationships are classrooms, not lifelong covenants. Learn, bless, and move on." },
  { "id": "inner_citadel_058", "category": "Inner Citadel", "text": "Your calm is more persuasive than your explanations." },
  { "id": "inner_citadel_059", "category": "Inner Citadel", "text": "Do not shrink your boundaries to fit someone else's chaos." },
  { "id": "inner_citadel_060", "category": "Inner Citadel", "text": "The mind that practices gratitude becomes difficult for darkness to inhabit." },
  { "id": "inner_citadel_061", "category": "Inner Citadel", "text": "You cannot walk in freedom while carrying every opinion like a chain." },
  { "id": "inner_citadel_062", "category": "Inner Citadel", "text": "Make your inner dialogue a place where God would gladly sit and listen." },
  { "id": "inner_citadel_063", "category": "Inner Citadel", "text": "Do not feed thoughts that starve your spirit." },
  { "id": "inner_citadel_064", "category": "Inner Citadel", "text": "Sometimes the bravest move is not to fight harder, but to walk away wiser." },
  { "id": "inner_citadel_065", "category": "Inner Citadel", "text": "Your emotions are real, but they are not all reliable." },
  { "id": "inner_citadel_066", "category": "Inner Citadel", "text": "Practice saying, \"This thought is not from God,\" and letting it pass." },
  { "id": "inner_citadel_067", "category": "Inner Citadel", "text": "The more time you spend in God's presence, the less easily your peace is stolen." },
  { "id": "inner_citadel_068", "category": "Inner Citadel", "text": "Whoever can manipulate your mood can steer your life. Take the wheel back." },
  { "id": "inner_citadel_069", "category": "Inner Citadel", "text": "Sometimes the test is not whether you can win, but whether you can stay gentle while you do." },
  { "id": "inner_citadel_070", "category": "Inner Citadel", "text": "You do not have to attend every memory that calls your name." },
  { "id": "inner_citadel_071", "category": "Inner Citadel", "text": "Let truth, not trauma, have the final say about who you are." },
  { "id": "inner_citadel_072", "category": "Inner Citadel", "text": "If a habit keeps dimming your light, it is not harmless." },
  { "id": "inner_citadel_073", "category": "Inner Citadel", "text": "The discipline you avoid today becomes the regret you carry tomorrow." },
  { "id": "inner_citadel_074", "category": "Inner Citadel", "text": "Stay close to people who respect your boundaries without needing a lecture." },
  { "id": "inner_citadel_075", "category": "Inner Citadel", "text": "You are allowed to grow beyond the version of you that people are comfortable with." },
  { "id": "inner_citadel_076", "category": "Inner Citadel", "text": "Every time you choose patience over pettiness, your citadel walls rise higher." },
  { "id": "inner_citadel_077", "category": "Inner Citadel", "text": "You cannot heal what you constantly excuse." },
  { "id": "inner_citadel_078", "category": "Inner Citadel", "text": "Let God teach you the difference between carrying a cross and carrying someone else's consequences." },
  { "id": "inner_citadel_079", "category": "Inner Citadel", "text": "Your time is a gate. Open it slowly." },
  { "id": "inner_citadel_080", "category": "Inner Citadel", "text": "Do not let nostalgia convince you to rebuild prisons you finally escaped." },
  { "id": "inner_citadel_081", "category": "Inner Citadel", "text": "The one who keeps their word to themselves becomes unshakable." },
  { "id": "inner_citadel_082", "category": "Inner Citadel", "text": "If peace leaves whenever a certain person enters, pay attention." },
  { "id": "inner_citadel_083", "category": "Inner Citadel", "text": "You can disagree without becoming divided inside yourself." },
  { "id": "inner_citadel_084", "category": "Inner Citadel", "text": "Some patterns are not demonic, just undisciplined. Bring them before God anyway." },
  { "id": "inner_citadel_085", "category": "Inner Citadel", "text": "You are not obliged to bleed for people who refuse to bandage their own wounds." },
  { "id": "inner_citadel_086", "category": "Inner Citadel", "text": "Let your convictions be heavier than your temptations." },
  { "id": "inner_citadel_087", "category": "Inner Citadel", "text": "You are free to leave the table where love is always something you have to earn." },
  { "id": "inner_citadel_088", "category": "Inner Citadel", "text": "A restless mind will call stillness boring; a healed mind will call it home." },
  { "id": "inner_citadel_089", "category": "Inner Citadel", "text": "You honor God when you stop letting people trample what He is growing in you." },
  { "id": "inner_citadel_090", "category": "Inner Citadel", "text": "The emotion that shouts first is rarely the one that is most faithful to the truth." },
  { "id": "inner_citadel_091", "category": "Inner Citadel", "text": "Do not let shame narrate chapters that God already finished with grace." },
  { "id": "inner_citadel_092", "category": "Inner Citadel", "text": "Your inner world is not a public park. It is a sanctuary." },
  { "id": "inner_citadel_093", "category": "Inner Citadel", "text": "You are not obligated to answer questions that are only asked to wound you." },
  { "id": "inner_citadel_094", "category": "Inner Citadel", "text": "Practice being unoffended; it is one of the rarest strengths." },
  { "id": "inner_citadel_095", "category": "Inner Citadel", "text": "Where your attention goes, your inner armies march." },
  { "id": "inner_citadel_096", "category": "Inner Citadel", "text": "You can love people deeply without letting their storms decide your weather." },
  { "id": "inner_citadel_097", "category": "Inner Citadel", "text": "If it costs you your clarity, it is too expensive." },
  { "id": "inner_citadel_098", "category": "Inner Citadel", "text": "The more you practice returning to God in small irritations, the stronger you'll stand in great trials." },
  { "id": "inner_citadel_099", "category": "Inner Citadel", "text": "Do not let one dark moment convince you that the whole castle is falling." },
  { "id": "inner_citadel_100", "category": "Inner Citadel", "text": "The mind submitted to truth does not stay long in the prison of lies." },
  { "id": "inner_citadel_101", "category": "Inner Citadel", "text": "You are not obligated to respond in the same spirit that confronts you." },
  { "id": "inner_citadel_102", "category": "Inner Citadel", "text": "The same God who calms the sea can calm your reactions if you hand them to Him." },
  { "id": "inner_citadel_103", "category": "Inner Citadel", "text": "Do not postpone your growth because others are comfortable with your old captivity." },
  { "id": "inner_citadel_104", "category": "Inner Citadel", "text": "The ability to be alone without feeling abandoned is a fortified gift." },
  { "id": "inner_citadel_105", "category": "Inner Citadel", "text": "You are allowed to say, \"That may be your opinion of me, but it is not God's.\"" },
  { "id": "inner_citadel_106", "category": "Inner Citadel", "text": "Every time you let truth overrule a lie, the walls of your inner citadel grow higher and brighter." },
  { "id": "inner_citadel_107", "category": "Inner Citadel", "text": "Your spirit was not designed to be ruled by notifications." },
  { "id": "inner_citadel_108", "category": "Inner Citadel", "text": "When God is the center, nothing on the edges gets to be king." }
];

export const godCraftedProverbsQuotes: StockQuote[] = [
  { "id": "gcp_001", "category": "God-Crafted Proverbs", "text": "Where fear ends, wisdom takes its first breath." },
  { "id": "gcp_002", "category": "God-Crafted Proverbs", "text": "God often answers with silence, because silence is the only language the heart will finally stop interrupting." },
  { "id": "gcp_003", "category": "God-Crafted Proverbs", "text": "A distracted mind cannot hear God, but a steady heart can hear Him anywhere." },
  { "id": "gcp_004", "category": "God-Crafted Proverbs", "text": "Your soul is older than your wounds." },
  { "id": "gcp_005", "category": "God-Crafted Proverbs", "text": "When the path disappears, walk by intention; God will redraw the road beneath you." },
  { "id": "gcp_006", "category": "God-Crafted Proverbs", "text": "You cannot outrun what God is trying to grow in you." },
  { "id": "gcp_007", "category": "God-Crafted Proverbs", "text": "Every time you choose compassion over pride, Heaven expands by one invisible inch." },
  { "id": "gcp_008", "category": "God-Crafted Proverbs", "text": "The soul whispers long before it screams. Listen early." },
  { "id": "gcp_009", "category": "God-Crafted Proverbs", "text": "Some of God's greatest gifts look like delays until the day they arrive." },
  { "id": "gcp_010", "category": "God-Crafted Proverbs", "text": "The path lifts beneath the courageous." },
  { "id": "gcp_011", "category": "God-Crafted Proverbs", "text": "You can plant seeds with effort, but only God can decide which ones become forests." },
  { "id": "gcp_012", "category": "God-Crafted Proverbs", "text": "Truth has a way of shining through even when the world prefers shadows." },
  { "id": "gcp_013", "category": "God-Crafted Proverbs", "text": "Your breath is a prayer even when your lips are still." },
  { "id": "gcp_014", "category": "God-Crafted Proverbs", "text": "The soul grows most in places where the mind feels lost." },
  { "id": "gcp_015", "category": "God-Crafted Proverbs", "text": "A proud heart learns nothing; a humble heart learns everything." },
  { "id": "gcp_016", "category": "God-Crafted Proverbs", "text": "God hides strength inside gentleness so the world cannot corrupt it." },
  { "id": "gcp_017", "category": "God-Crafted Proverbs", "text": "The moment you choose honesty, the exile ends." },
  { "id": "gcp_018", "category": "God-Crafted Proverbs", "text": "Not every battle is yours; some are invitations to step aside and trust." },
  { "id": "gcp_019", "category": "God-Crafted Proverbs", "text": "Where your attention rests, your destiny roots." },
  { "id": "gcp_020", "category": "God-Crafted Proverbs", "text": "God writes straight even with trembling hands." },
  { "id": "gcp_021", "category": "God-Crafted Proverbs", "text": "The heart that forgives walks lighter than the one that wins." },
  { "id": "gcp_022", "category": "God-Crafted Proverbs", "text": "Your spirit recognizes truth before your mind admits it." },
  { "id": "gcp_023", "category": "God-Crafted Proverbs", "text": "Patience is not waiting; patience is trusting while you move." },
  { "id": "gcp_024", "category": "God-Crafted Proverbs", "text": "Every sunrise is an unopened letter from God." },
  { "id": "gcp_025", "category": "God-Crafted Proverbs", "text": "Do not fear slow progress; fear standing still in a place God asked you to leave." },
  { "id": "gcp_026", "category": "God-Crafted Proverbs", "text": "Wisdom is the art of overhearing God's instructions." },
  { "id": "gcp_027", "category": "God-Crafted Proverbs", "text": "Where gratitude dwells, despair cannot build a nest." },
  { "id": "gcp_028", "category": "God-Crafted Proverbs", "text": "Your spirit grows best in rooms where your ego is uncomfortable." },
  { "id": "gcp_029", "category": "God-Crafted Proverbs", "text": "God never wastes a surrender." },
  { "id": "gcp_030", "category": "God-Crafted Proverbs", "text": "When wisdom knocks, pride pretends not to hear." },
  { "id": "gcp_031", "category": "God-Crafted Proverbs", "text": "Peace is not found; it is practiced." },
  { "id": "gcp_032", "category": "God-Crafted Proverbs", "text": "God walks slower than anxiety but arrives sooner than fear." },
  { "id": "gcp_033", "category": "God-Crafted Proverbs", "text": "Your soul expands every time you choose kindness when anger was easier." },
  { "id": "gcp_034", "category": "God-Crafted Proverbs", "text": "The right path rarely feels comfortable at the beginning." },
  { "id": "gcp_035", "category": "God-Crafted Proverbs", "text": "Humility is the password to wisdom." },
  { "id": "gcp_036", "category": "God-Crafted Proverbs", "text": "Where your feet hesitate, your faith must step." },
  { "id": "gcp_037", "category": "God-Crafted Proverbs", "text": "Every act done without love becomes a burden. Every act done with love becomes worship." },
  { "id": "gcp_038", "category": "God-Crafted Proverbs", "text": "Sometimes God closes doors because your prayers were asking for halls." },
  { "id": "gcp_039", "category": "God-Crafted Proverbs", "text": "Your mind cannot outrun the wisdom your heart already carries." },
  { "id": "gcp_040", "category": "God-Crafted Proverbs", "text": "The soul sees farther when the eyes are tired." },
  { "id": "gcp_041", "category": "God-Crafted Proverbs", "text": "Every storm reveals what was never anchored." },
  { "id": "gcp_042", "category": "God-Crafted Proverbs", "text": "Joy takes practice, just like strength." },
  { "id": "gcp_043", "category": "God-Crafted Proverbs", "text": "God does not measure you by speed, but by sincerity." },
  { "id": "gcp_044", "category": "God-Crafted Proverbs", "text": "You are not empty—you are being prepared for what fits." },
  { "id": "gcp_045", "category": "God-Crafted Proverbs", "text": "A single honest prayer clears more darkness than a thousand loud philosophies." },
  { "id": "gcp_046", "category": "God-Crafted Proverbs", "text": "When the heart is quiet, God's voice becomes obvious." },
  { "id": "gcp_047", "category": "God-Crafted Proverbs", "text": "Your spirit grows every time you choose the harder right over the easier wrong." },
  { "id": "gcp_048", "category": "God-Crafted Proverbs", "text": "Forgiveness does not excuse the past; it releases the future." },
  { "id": "gcp_049", "category": "God-Crafted Proverbs", "text": "Some lessons come wrapped in discomfort; open them anyway." },
  { "id": "gcp_050", "category": "God-Crafted Proverbs", "text": "God's timing is late only to those who trust their clocks more than His wisdom." },
  { "id": "gcp_051", "category": "God-Crafted Proverbs", "text": "Your soul is a lantern; clean the glass, not the flame." },
  { "id": "gcp_052", "category": "God-Crafted Proverbs", "text": "The path of truth is narrow because few choose to carry less." },
  { "id": "gcp_053", "category": "God-Crafted Proverbs", "text": "Confusion is often clarity in disguise, asking you to slow down." },
  { "id": "gcp_054", "category": "God-Crafted Proverbs", "text": "When God expands your heart, He first makes room by removing what you cling to." }
];

export const STOCK_PACKS: StockQuote[] = [
  ...radiantResolveQuotes,
  ...gritAndGloryQuotes,
  ...sanctifiedFireQuotes,
  ...visionQuestQuotes,
  ...christwardFlameQuotes,
  ...innerCitadelQuotes,
  ...godCraftedProverbsQuotes,
  // 🔻 FUTURE PACKS WILL BE APPENDED HERE 🔻
];

export function getStockQuotesForForge(): ForgeQuote[] {
  return STOCK_PACKS.map((q) => ({
    id: `stock:${q.id}`,
    fileId: `stock:${q.category}`,
    fileName: q.category,
    text: q.text.trim(),
    index: 0,
    length: q.text.trim().length,
  }));
}
