import type { ForgeQuote } from "./forgeRandomEngine";

export type StockQuote = {
  id: string;
  category: string;
  text: string;
};

export const radiantResolveQuotes: StockQuote[] = [
  { "id": "radiant_resolve_001", "category": "Radiant Resolve", "text": "You have survived every single day you thought you couldn't. Remember that." },
  { "id": "radiant_resolve_002", "category": "Radiant Resolve", "text": "Today will not defeat you; it will reveal how unbreakable you really are." },
  { "id": "radiant_resolve_003", "category": "Radiant Resolve", "text": "Your future self is already cheering for you. Don't walk away from them." },
  { "id": "radiant_resolve_004", "category": "Radiant Resolve", "text": "You are not behind; you are precisely on the step you are learning from." },
  { "id": "radiant_resolve_005", "category": "Radiant Resolve", "text": "Every tiny, unseen effort is quietly building the life you keep praying for." },
  { "id": "radiant_resolve_006", "category": "Radiant Resolve", "text": "Courage rarely feels like roaring; most days it feels like showing up anyway." },
  { "id": "radiant_resolve_007", "category": "Radiant Resolve", "text": "You are allowed to be both exhausted and unstoppable at the very same time." },
  { "id": "radiant_resolve_008", "category": "Radiant Resolve", "text": "Do not underestimate the holy power of simply trying again today." },
  { "id": "radiant_resolve_009", "category": "Radiant Resolve", "text": "Your pace is sacred. Rushing will not deliver you where grace is leading." },
  { "id": "radiant_resolve_010", "category": "Radiant Resolve", "text": "Even on days you feel dim, you are still a lamp lit by Eternity." },
  { "id": "radiant_resolve_011", "category": "Radiant Resolve", "text": "You don't need to see the whole road; you just need one honest step." },
  { "id": "radiant_resolve_012", "category": "Radiant Resolve", "text": "There is a version of you on the other side of this that is grateful you stayed." },
  { "id": "radiant_resolve_013", "category": "Radiant Resolve", "text": "You are not failing; you are forging. Fire never feels like progress at first." },
  { "id": "radiant_resolve_014", "category": "Radiant Resolve", "text": "The mountain ahead is not an enemy; it is the shape of your next strength." },
  { "id": "radiant_resolve_015", "category": "Radiant Resolve", "text": "Showing up with a shaking heart still counts as showing up with courage." },
  { "id": "radiant_resolve_016", "category": "Radiant Resolve", "text": "Every time you choose love over fear, the universe quietly adjusts around you." },
  { "id": "radiant_resolve_017", "category": "Radiant Resolve", "text": "You are allowed to rest; you are not allowed to believe you are worthless." },
  { "id": "radiant_resolve_018", "category": "Radiant Resolve", "text": "Your heart has been broken, but it still believes in light. That is power." },
  { "id": "radiant_resolve_019", "category": "Radiant Resolve", "text": "You have no idea how many people are breathing easier because you exist." },
  { "id": "radiant_resolve_020", "category": "Radiant Resolve", "text": "Progress is often disguised as repetition. Don't despise the quiet training grounds." },
  { "id": "radiant_resolve_021", "category": "Radiant Resolve", "text": "You can start again without hating who you were when you fell." },
  { "id": "radiant_resolve_022", "category": "Radiant Resolve", "text": "It's okay if your miracle today is simply that you did not give up." },
  { "id": "radiant_resolve_023", "category": "Radiant Resolve", "text": "You are not too late; you are right on time to choose a different direction." },
  { "id": "radiant_resolve_024", "category": "Radiant Resolve", "text": "The same soul that survived yesterday can be trusted to navigate today." },
  { "id": "radiant_resolve_025", "category": "Radiant Resolve", "text": "Do not compare your raw, sacred process to someone else's edited highlight reel." },
  { "id": "radiant_resolve_026", "category": "Radiant Resolve", "text": "You are not fragile; you are finely made. There is a difference." },
  { "id": "radiant_resolve_027", "category": "Radiant Resolve", "text": "Sometimes the bravest thing you can say is, 'I will try again tomorrow.'" },
  { "id": "radiant_resolve_028", "category": "Radiant Resolve", "text": "Your wounds are not the end of your story; they are the ink of your testimony." },
  { "id": "radiant_resolve_029", "category": "Radiant Resolve", "text": "When everything feels heavy, carry only the next right choice." },
  { "id": "radiant_resolve_030", "category": "Radiant Resolve", "text": "You were not sent here to impress everyone; you were sent here to awaken." },
  { "id": "radiant_resolve_031", "category": "Radiant Resolve", "text": "Even if you whisper your prayer, Heaven still hears it at full volume." },
  { "id": "radiant_resolve_032", "category": "Radiant Resolve", "text": "Your limitations are real, but so is the grace that keeps expanding them." },
  { "id": "radiant_resolve_033", "category": "Radiant Resolve", "text": "You are not just getting through this; you are being quietly remade by it." },
  { "id": "radiant_resolve_034", "category": "Radiant Resolve", "text": "Let go of who you were supposed to be and serve who you are becoming." },
  { "id": "radiant_resolve_035", "category": "Radiant Resolve", "text": "Your smallest consistent effort will outrun your loudest occasional burst." },
  { "id": "radiant_resolve_036", "category": "Radiant Resolve", "text": "Some seasons are not about blooming; they are about growing roots in secret." },
  { "id": "radiant_resolve_037", "category": "Radiant Resolve", "text": "You have permission to be a work in progress and a masterpiece simultaneously." },
  { "id": "radiant_resolve_038", "category": "Radiant Resolve", "text": "Remember how far you've come; even your starting line was once a distant dream." },
  { "id": "radiant_resolve_039", "category": "Radiant Resolve", "text": "You are allowed to protect your peace like it is something holy—because it is." },
  { "id": "radiant_resolve_040", "category": "Radiant Resolve", "text": "Every 'I can't' you've said before was followed by a moment where you actually did." },
  { "id": "radiant_resolve_041", "category": "Radiant Resolve", "text": "The heaviness you feel is not weakness; it is the weight of transformation." },
  { "id": "radiant_resolve_042", "category": "Radiant Resolve", "text": "Do not rush out of the cocoon. Wings need time to remember what they are." },
  { "id": "radiant_resolve_043", "category": "Radiant Resolve", "text": "Some days your only job is to keep the flame of hope from going out." },
  { "id": "radiant_resolve_044", "category": "Radiant Resolve", "text": "You are not your worst decision; you are your next surrendered choice." },
  { "id": "radiant_resolve_045", "category": "Radiant Resolve", "text": "You can't always control the storm, but you can anchor where you tie your heart." },
  { "id": "radiant_resolve_046", "category": "Radiant Resolve", "text": "You did not lose time; you gathered wisdom you could not have learned otherwise." },
  { "id": "radiant_resolve_047", "category": "Radiant Resolve", "text": "Be gentle with yourself; you are carrying chapters only God has fully read." },
  { "id": "radiant_resolve_048", "category": "Radiant Resolve", "text": "Every time you choose to heal instead of hide, you bless people you haven't met yet." },
  { "id": "radiant_resolve_049", "category": "Radiant Resolve", "text": "Your value has never depended on how well today is going." },
  { "id": "radiant_resolve_050", "category": "Radiant Resolve", "text": "You are more than the story your fear tells about you." },
  { "id": "radiant_resolve_051", "category": "Radiant Resolve", "text": "The same light that made the stars is patient with your slow, holy progress." },
  { "id": "radiant_resolve_052", "category": "Radiant Resolve", "text": "Even when you feel scattered, your soul is still held in perfect order." },
  { "id": "radiant_resolve_053", "category": "Radiant Resolve", "text": "You don't need louder motivation; you need a deeper why. You already have it." },
  { "id": "radiant_resolve_054", "category": "Radiant Resolve", "text": "You have walked through nights that would have swallowed other people whole." },
  { "id": "radiant_resolve_055", "category": "Radiant Resolve", "text": "Your tears have never been a sign of failure; they are evidence you still care." },
  { "id": "radiant_resolve_056", "category": "Radiant Resolve", "text": "There is a quiet, undefeatable core inside you that remembers why you're here." },
  { "id": "radiant_resolve_057", "category": "Radiant Resolve", "text": "You are stronger than the thing that tried to convince you to quit." },
  { "id": "radiant_resolve_058", "category": "Radiant Resolve", "text": "You don't have to fix everything today; you just have to stay available to grace." },
  { "id": "radiant_resolve_059", "category": "Radiant Resolve", "text": "Even when you feel lost, you are still on a map Heaven understands perfectly." },
  { "id": "radiant_resolve_060", "category": "Radiant Resolve", "text": "You are not empty; you are being cleared for something wild and beautiful." },
  { "id": "radiant_resolve_061", "category": "Radiant Resolve", "text": "Some of your greatest breakthroughs will look like very ordinary Tuesdays at first." },
  { "id": "radiant_resolve_062", "category": "Radiant Resolve", "text": "You are allowed to be proud of how quietly you kept choosing the light." },
  { "id": "radiant_resolve_063", "category": "Radiant Resolve", "text": "Your heart is not a burden; it is the compass that keeps saving your life." },
  { "id": "radiant_resolve_064", "category": "Radiant Resolve", "text": "You have survived storms that never made it into your biography. Heaven saw them all." },
  { "id": "radiant_resolve_065", "category": "Radiant Resolve", "text": "If you can still love after everything, you are walking in rare power." },
  { "id": "radiant_resolve_066", "category": "Radiant Resolve", "text": "You're not starting from scratch; you're starting from experience. That is leverage." },
  { "id": "radiant_resolve_067", "category": "Radiant Resolve", "text": "Let today be proof that you can move gently and still move forward." },
  { "id": "radiant_resolve_068", "category": "Radiant Resolve", "text": "You are never disqualified from beginning again in the eyes of Love." },
  { "id": "radiant_resolve_069", "category": "Radiant Resolve", "text": "You are not late; you are layered. Your story needed this depth." },
  { "id": "radiant_resolve_070", "category": "Radiant Resolve", "text": "You do not need everyone to believe in you; just refuse to abandon yourself." },
  { "id": "radiant_resolve_071", "category": "Radiant Resolve", "text": "Every time you choose healing over repeating, the whole lineage breathes easier." },
  { "id": "radiant_resolve_072", "category": "Radiant Resolve", "text": "You are tougher than your mood, kinder than your fears, and deeper than your doubts." },
  { "id": "radiant_resolve_073", "category": "Radiant Resolve", "text": "You deserved gentleness even on the days you only offered yourself survival." },
  { "id": "radiant_resolve_074", "category": "Radiant Resolve", "text": "The dark tried to convince you it was permanent. Look at you, still glowing." },
  { "id": "radiant_resolve_075", "category": "Radiant Resolve", "text": "You have not missed your moment; you are slowly becoming the person who can hold it." },
  { "id": "radiant_resolve_076", "category": "Radiant Resolve", "text": "Even if no one claps today, your courage still shook something in the unseen." },
  { "id": "radiant_resolve_077", "category": "Radiant Resolve", "text": "You are allowed to outgrow spaces that keep asking you to shrink." },
  { "id": "radiant_resolve_078", "category": "Radiant Resolve", "text": "May you never again confuse chaos with passion or anxiety with destiny." },
  { "id": "radiant_resolve_079", "category": "Radiant Resolve", "text": "You can be sacred and sweaty, holy and human, radiant and very much in process." },
  { "id": "radiant_resolve_080", "category": "Radiant Resolve", "text": "Your heart keeps choosing compassion in a world that rewards apathy. That's heroic." },
  { "id": "radiant_resolve_081", "category": "Radiant Resolve", "text": "You are not here to win every argument; you are here to keep your soul alive." },
  { "id": "radiant_resolve_082", "category": "Radiant Resolve", "text": "You can honor your pain without letting it rewrite your identity." },
  { "id": "radiant_resolve_083", "category": "Radiant Resolve", "text": "Healing is not linear, but it is real. Look at how your reactions are changing." },
  { "id": "radiant_resolve_084", "category": "Radiant Resolve", "text": "You are not the chaos you walked through; you are the calm you are learning to keep." },
  { "id": "radiant_resolve_085", "category": "Radiant Resolve", "text": "You can be shaking and still step forward. Nerves don't cancel destiny." },
  { "id": "radiant_resolve_086", "category": "Radiant Resolve", "text": "Your dreams are not random; they are coordinates to the work your soul came to do." },
  { "id": "radiant_resolve_087", "category": "Radiant Resolve", "text": "The page you're on right now would once have looked impossible. Honor it." },
  { "id": "radiant_resolve_088", "category": "Radiant Resolve", "text": "You can set boundaries without apologizing for needing oxygen for your soul." },
  { "id": "radiant_resolve_089", "category": "Radiant Resolve", "text": "You keep thinking you're starting over; really, you're starting higher each time." },
  { "id": "radiant_resolve_090", "category": "Radiant Resolve", "text": "You are not too much; you are precisely the size of the calling on your life." },
  { "id": "radiant_resolve_091", "category": "Radiant Resolve", "text": "The gentleness you crave from others—offer a fraction of it to yourself today." },
  { "id": "radiant_resolve_092", "category": "Radiant Resolve", "text": "You didn't come this far to only rebuild the same cage from prettier materials." },
  { "id": "radiant_resolve_093", "category": "Radiant Resolve", "text": "You are strong enough to choose the slower, truer path instead of the quick escape." },
  { "id": "radiant_resolve_094", "category": "Radiant Resolve", "text": "Every time you return to love after disappointment, you rewrite what's possible." },
  { "id": "radiant_resolve_095", "category": "Radiant Resolve", "text": "You don't need all the answers; you need the courage to live inside the questions." },
  { "id": "radiant_resolve_096", "category": "Radiant Resolve", "text": "Your scars are proof that light reached you in time, not that darkness won." },
  { "id": "radiant_resolve_097", "category": "Radiant Resolve", "text": "You can forgive yourself without pretending you didn't know better. Growth hurts." },
  { "id": "radiant_resolve_098", "category": "Radiant Resolve", "text": "Sometimes strength is not moving on; it is staying present with what still aches." },
  { "id": "radiant_resolve_099", "category": "Radiant Resolve", "text": "You are allowed to glow differently than people expected. Your path is bespoke." },
  { "id": "radiant_resolve_100", "category": "Radiant Resolve", "text": "You are not surviving by accident; you are here because Love keeps choosing you." },
  { "id": "radiant_resolve_101", "category": "Radiant Resolve", "text": "Your soul remembers a joy deeper than this moment's confusion. Lean toward that." },
  { "id": "radiant_resolve_102", "category": "Radiant Resolve", "text": "You can be tired and still anointed, drained and still undeniably chosen for this." },
  { "id": "radiant_resolve_103", "category": "Radiant Resolve", "text": "Every time you choose honesty over hiding, your future becomes a little lighter." },
  { "id": "radiant_resolve_104", "category": "Radiant Resolve", "text": "You are not alone in this; invisible hands have been steadying you for years." },
  { "id": "radiant_resolve_105", "category": "Radiant Resolve", "text": "The fact that you still care about goodness after everything is a victory." },
  { "id": "radiant_resolve_106", "category": "Radiant Resolve", "text": "You are not unfinished because you are imperfect; you are alive, therefore evolving." },
  { "id": "radiant_resolve_107", "category": "Radiant Resolve", "text": "There is nothing ordinary about a heart that keeps rising after invisible wars." },
  { "id": "radiant_resolve_108", "category": "Radiant Resolve", "text": "Your existence is already a miracle; everything else is just detail and devotion." }
];

export const gritAndGloryQuotes: StockQuote[] = [
  { id: "grit_glory_001", category: "Grit & Glory", text: "Discipline is choosing what you want most over what you want right now." },
  { id: "grit_glory_002", category: "Grit & Glory", text: "You don't rise to the level of your dreams; you fall to the level of your habits." },
  { id: "grit_glory_003", category: "Grit & Glory", text: "Champions are built in the hours no one is watching." },
  { id: "grit_glory_004", category: "Grit & Glory", text: "You won't always be motivated; learn to be moved by commitment instead." },
  { id: "grit_glory_005", category: "Grit & Glory", text: "The grind is simply the prayer of the body saying, \"I refuse to stay the same.\"" },
  { id: "grit_glory_006", category: "Grit & Glory", text: "Every rep is a sentence in the story of who you are becoming." },
  { id: "grit_glory_007", category: "Grit & Glory", text: "You can suffer the pain of discipline or the pain of regret—both hurt, but only one transforms you." },
  { id: "grit_glory_008", category: "Grit & Glory", text: "Excuses are the most expensive things you can buy with your potential." },
  { id: "grit_glory_009", category: "Grit & Glory", text: "Sweat is your old self leaving the body." },
  { id: "grit_glory_010", category: "Grit & Glory", text: "It's not supposed to be easy. It's supposed to be worth it." },
  { id: "grit_glory_011", category: "Grit & Glory", text: "The difference between almost and unstoppable is usually ten more minutes." },
  { id: "grit_glory_012", category: "Grit & Glory", text: "Your body hears everything your mind whispers. Tell it you are not done yet." },
  { id: "grit_glory_013", category: "Grit & Glory", text: "Progress doesn't ask if you're in the mood; it asks if you showed up." },
  { id: "grit_glory_014", category: "Grit & Glory", text: "You don't find your limits by thinking about them; you find them by testing them." },
  { id: "grit_glory_015", category: "Grit & Glory", text: "The weight is not your enemy; it is the sculptor of your future strength." },
  { id: "grit_glory_016", category: "Grit & Glory", text: "One hard choice a day writes a completely different life in a year." },
  { id: "grit_glory_017", category: "Grit & Glory", text: "If it doesn't challenge you, it will never be allowed to change you." },
  { id: "grit_glory_018", category: "Grit & Glory", text: "You are not chasing perfection; you are chasing progression." },
  { id: "grit_glory_019", category: "Grit & Glory", text: "The body grows where the mind refuses to quit." },
  { id: "grit_glory_020", category: "Grit & Glory", text: "You can't control the genetics you were given, but you control the work you bring." },
  { id: "grit_glory_021", category: "Grit & Glory", text: "Consistency is heavier than any dumbbell you'll ever lift." },
  { id: "grit_glory_022", category: "Grit & Glory", text: "When you want to quit, remember the days you prayed for this level of strength." },
  { id: "grit_glory_023", category: "Grit & Glory", text: "Your comfort zone is a beautiful place where nothing new ever grows." },
  { id: "grit_glory_024", category: "Grit & Glory", text: "You don't have to feel like it to act like it." },
  { id: "grit_glory_025", category: "Grit & Glory", text: "Every drop of sweat is a small down payment on the future you want to inhabit." },
  { id: "grit_glory_026", category: "Grit & Glory", text: "Stop negotiating with the part of you that wants to stay average." },
  { id: "grit_glory_027", category: "Grit & Glory", text: "Your lungs burning is just your soul expanding its territory." },
  { id: "grit_glory_028", category: "Grit & Glory", text: "You will not always see the results, but your nervous system is counting every rep." },
  { id: "grit_glory_029", category: "Grit & Glory", text: "You are stronger than the story your fatigue is telling." },
  { id: "grit_glory_030", category: "Grit & Glory", text: "Most people quit at discomfort; champions move in when everyone else checks out." },
  { id: "grit_glory_031", category: "Grit & Glory", text: "You are not fragile; you are under construction." },
  { id: "grit_glory_032", category: "Grit & Glory", text: "Nothing hits harder than the realization that you could have gone harder." },
  { id: "grit_glory_033", category: "Grit & Glory", text: "Train so the voice that says \"I can't\" gets drowned out by evidence that you can." },
  { id: "grit_glory_034", category: "Grit & Glory", text: "Your future PRs are hiding behind today's warm-up." },
  { id: "grit_glory_035", category: "Grit & Glory", text: "The gym is where you practice not running away from difficulty." },
  { id: "grit_glory_036", category: "Grit & Glory", text: "The mirror shows the surface; your discipline shows the truth." },
  { id: "grit_glory_037", category: "Grit & Glory", text: "Motivation might start you; systems keep you moving when the feeling evaporates." },
  { id: "grit_glory_038", category: "Grit & Glory", text: "You are not trying to look strong—you are becoming someone who *is* strong." },
  { id: "grit_glory_039", category: "Grit & Glory", text: "Your warm-up is someone else's max; stay humble, stay hungry." },
  { id: "grit_glory_040", category: "Grit & Glory", text: "You are allowed to rest. You are not allowed to permanently retreat." },
  { id: "grit_glory_041", category: "Grit & Glory", text: "There is a part of you that only wakes up under heavy load. Meet them often." },
  { id: "grit_glory_042", category: "Grit & Glory", text: "Training is a daily vote cast for the future version of you." },
  { id: "grit_glory_043", category: "Grit & Glory", text: "You won't always feel like a warrior. Train until that doesn't matter." },
  { id: "grit_glory_044", category: "Grit & Glory", text: "Your body listens more to what you repeat than to what you promise." },
  { id: "grit_glory_045", category: "Grit & Glory", text: "The best pre-workout is remembering who you said you would become." },
  { id: "grit_glory_046", category: "Grit & Glory", text: "You didn't come this far to just rehearse your excuses in better shape." },
  { id: "grit_glory_047", category: "Grit & Glory", text: "The iron doesn't lie; it simply reflects your relationship with effort." },
  { id: "grit_glory_048", category: "Grit & Glory", text: "Your muscles don't care about your mood; they respond to stimulus and consistency." },
  { id: "grit_glory_049", category: "Grit & Glory", text: "You get to decide if this rep is forgettable or foundational." },
  { id: "grit_glory_050", category: "Grit & Glory", text: "Pain is a language. Learn when it says \"adapt\" instead of \"stop.\"" },
  { id: "grit_glory_051", category: "Grit & Glory", text: "You are teaching your nervous system that hard things are survivable." },
  { id: "grit_glory_052", category: "Grit & Glory", text: "You are not just building strength; you are building evidence you can rely on yourself." },
  { id: "grit_glory_053", category: "Grit & Glory", text: "Fall in love with the session, not just the selfie." },
  { id: "grit_glory_054", category: "Grit & Glory", text: "You can't outsource the work, but you also can't outsource the pride." },
  { id: "grit_glory_055", category: "Grit & Glory", text: "The version of you that never quits is forged one stubborn set at a time." },
  { id: "grit_glory_056", category: "Grit & Glory", text: "Talent sets your starting line; grit keeps moving the finish line." },
  { id: "grit_glory_057", category: "Grit & Glory", text: "You can be sore and grateful at the same time." },
  { id: "grit_glory_058", category: "Grit & Glory", text: "When motivation dies, let routine inherit the throne." },
  { id: "grit_glory_059", category: "Grit & Glory", text: "Every time you train when you don't feel like it, you steal a victory from your weaker self." },
  { id: "grit_glory_060", category: "Grit & Glory", text: "Those last ugly reps are where the future you is built." },
  { id: "grit_glory_061", category: "Grit & Glory", text: "You're not chasing a look; you're forging a lifestyle." },
  { id: "grit_glory_062", category: "Grit & Glory", text: "A bad workout still beats the best intention that never left the couch." },
  { id: "grit_glory_063", category: "Grit & Glory", text: "You are not defined by the weight you lift, but by the weight you refuse to avoid." },
  { id: "grit_glory_064", category: "Grit & Glory", text: "Every skipped session is a vote for who you said you didn't want to be." },
  { id: "grit_glory_065", category: "Grit & Glory", text: "You are allowed to be a beginner and still train like your future depends on it." },
  { id: "grit_glory_066", category: "Grit & Glory", text: "Your body becomes a journal of every choice you quietly made." },
  { id: "grit_glory_067", category: "Grit & Glory", text: "You're not weak—you're just pre-strong." },
  { id: "grit_glory_068", category: "Grit & Glory", text: "The heaviest weight in the room is often the door you don't walk through." },
  { id: "grit_glory_069", category: "Grit & Glory", text: "Every season of training teaches you a different dialect of discipline." },
  { id: "grit_glory_070", category: "Grit & Glory", text: "You don't need a perfect plan; you need an honest set of reps today." },
  { id: "grit_glory_071", category: "Grit & Glory", text: "You didn't lose momentum; you paused. Now decide what kind of restart this is." },
  { id: "grit_glory_072", category: "Grit & Glory", text: "Your breath might be heavy, but your excuses are heavier." },
  { id: "grit_glory_073", category: "Grit & Glory", text: "A year from now, your current level could be your warm-up." },
  { id: "grit_glory_074", category: "Grit & Glory", text: "You are always one session away from rewriting the story of your day." },
  { id: "grit_glory_075", category: "Grit & Glory", text: "You can outwork a lot of genetics and all of your excuses." },
  { id: "grit_glory_076", category: "Grit & Glory", text: "Treat your training time like a sacred appointment with your future self." },
  { id: "grit_glory_077", category: "Grit & Glory", text: "Your body is not the enemy; it is the ally that needs consistent leadership." },
  { id: "grit_glory_078", category: "Grit & Glory", text: "You'll stop underestimating yourself the day you stop quitting early." },
  { id: "grit_glory_079", category: "Grit & Glory", text: "No one can gift you resilience; you must forge it under load." },
  { id: "grit_glory_080", category: "Grit & Glory", text: "Progress is often invisible until the day it suddenly isn't." },
  { id: "grit_glory_081", category: "Grit & Glory", text: "You can't control whether it's a \"good day\"—you can control if it's a day you trained." },
  { id: "grit_glory_082", category: "Grit & Glory", text: "You are allowed to take breaks; just don't make them your new personality." },
  { id: "grit_glory_083", category: "Grit & Glory", text: "Act like someone who respects the gift of having a body that can still move." },
  { id: "grit_glory_084", category: "Grit & Glory", text: "Treat your reps as if your children will inherit your discipline." },
  { id: "grit_glory_085", category: "Grit & Glory", text: "Your goals are not distant; they're stacked in the sets you skip or complete." },
  { id: "grit_glory_086", category: "Grit & Glory", text: "There is a quiet kind of glory in doing the right thing when nobody will know." },
  { id: "grit_glory_087", category: "Grit & Glory", text: "You're not \"starting over\"—you're starting wiser, and that changes everything." },
  { id: "grit_glory_088", category: "Grit & Glory", text: "The iron does not care about your past. It only responds to what you lift today." },
  { id: "grit_glory_089", category: "Grit & Glory", text: "The work never gets easier; you simply grow into someone it can't intimidate." },
  { id: "grit_glory_090", category: "Grit & Glory", text: "Show up especially on the days your mind invents the best reasons not to." },
  { id: "grit_glory_091", category: "Grit & Glory", text: "You are building a life where \"I don't feel like it\" no longer gets a vote." },
  { id: "grit_glory_092", category: "Grit & Glory", text: "Remember why you started, then train like you never want to go back." },
  { id: "grit_glory_093", category: "Grit & Glory", text: "Pain that comes from growth is a different species than pain that comes from avoidance." },
  { id: "grit_glory_094", category: "Grit & Glory", text: "One hard hour in the gym can silence a full day of self-doubt." },
  { id: "grit_glory_095", category: "Grit & Glory", text: "There is no hack that replaces time under tension." },
  { id: "grit_glory_096", category: "Grit & Glory", text: "You either make time for training or you make peace with shrinking." },
  { id: "grit_glory_097", category: "Grit & Glory", text: "Let the soreness remind you that you showed up when you could have checked out." },
  { id: "grit_glory_098", category: "Grit & Glory", text: "Stop romanticizing the idea of change and start romanticizing the act of effort." },
  { id: "grit_glory_099", category: "Grit & Glory", text: "Your greatest flex will always be self-mastery." },
  { id: "grit_glory_100", category: "Grit & Glory", text: "Treat every set like a small rebellion against the version of you that settles." },
  { id: "grit_glory_101", category: "Grit & Glory", text: "You are not chasing aesthetics; you are building an instrument for your mission." },
  { id: "grit_glory_102", category: "Grit & Glory", text: "There will never be a perfect time. There will always be a next rep." },
  { id: "grit_glory_103", category: "Grit & Glory", text: "You can train angry, tired, or unsure. You just can't train absent." },
  { id: "grit_glory_104", category: "Grit & Glory", text: "The gym is the altar where procrastination is sacrificed one set at a time." },
  { id: "grit_glory_105", category: "Grit & Glory", text: "Every session you finish is another reason to trust yourself." },
  { id: "grit_glory_106", category: "Grit & Glory", text: "Grit is the art of staying when your comfort has already left the building." },
  { id: "grit_glory_107", category: "Grit & Glory", text: "The day you stop giving up on yourself mid-set is the day everything else changes." },
  { id: "grit_glory_108", category: "Grit & Glory", text: "Glory is not found on the podium; it's found in the thousand quiet choices to keep going." }
];

export const STOCK_PACKS: StockQuote[] = [
  ...radiantResolveQuotes,
  ...gritAndGloryQuotes,
  // 🔻 FUTURE PACKS WILL BE APPENDED HERE 🔻
];

export function getStockQuotesForForge(): ForgeQuote[] {
  return STOCK_PACKS.map((q) => ({
    id: `stock:${q.id}`,
    fileId: `stock:${q.category}`,
    fileName: q.category,
    text: q.text.trim(),
    index: 0,
    length: q.text.trim().length,
  }));
}
